### ISSUE TITLE
[iOS] Must slide up on field in order to make drop down display 

### ISSUE THREAD

**Issue by spstratis** [PeterStaev/NativeScript-Drop-Down#105]
**Plugin Version**
 nativescript-drop-down: 1.5.3

**Issue**
On iOS I'm having an issue where in order to get the drop dropdown to display, I have to slide my finger up on the fields rather than tapping it in order for it the list of items to show up. This is occurring on a page which contains 3 separate fields which use the drop-down ability. Here is a snippet of the xml where I'm using the plugin, as well as a gist of the full views xml for context. 

```
          <ios>
            <WrapLayout orientation="horizontal" itemWidth="" itemHeight="">
             <StackLayout class="dp-wrapper">
                <dd:DropDown id="date-picker" items="{{ days }}" selectedIndex="{{ dayIndex }}" />
                <StackLayout class="hr-dark"></StackLayout>
              </StackLayout>
              <StackLayout class="dp-wrapper">
                <dd:DropDown id="date-picker" items="{{ months }}" selectedIndex="{{ monthIndex }}" />                            
                <StackLayout class="hr-dark"></StackLayout>
              </StackLayout>
              <StackLayout class="dp-wrapper">
                <dd:DropDown id="date-picker" items="{{ years }}" selectedIndex="{{ yearIndex }}" /> 
                <StackLayout class="hr-dark"></StackLayout>
              </StackLayout>  
            </WrapLayout>
          </ios> 
```
Gist for context: https://gist.github.com/spstratis/125554c8f80f6eeb9f9076b7d9aaccb4

I'm using the plugin on a separate view which only contains one drop-down field and the standard taping of it brings up the dropdown list with out any issues.

**Comment by PeterStaev** [comment]
Hey @spstratis , I will not be supporting the pre-3.0 version. I've just tried your setup in the demo app and it works ok, so it must either be some problem with the old version, or something else in your setup.
