### ISSUE TITLE
text-align css property is not applied on iOS

### ISSUE THREAD

**Issue by terreb** [PeterStaev/NativeScript-Drop-Down#11]
text-align css property doesn't work on iOS.

    <dd:DropDown items="{{ items}}" selectedIndex="{{ index }}" class="drop-down" />

css:

    .drop-down {
        background-color: #fff;    /* works */
        horizontal-align: right;     /* works */
        vertical-align: center;      /* works */
        text-align: center;            /* doesn't work */
        width: 100;                      /* works */
        height: 36;                      /* works */
    }

**Comment by PeterStaev** [comment]
The new version on NPM (1.2.4) fixes this.
