### ISSUE TITLE
how do i get value of selected index drop down..? i iterate my Items={{menuList}} from Database.please help me to get selected index items value.   thank you in advance

### ISSUE THREAD

**Issue by akshaydoiphode** [PeterStaev/NativeScript-Drop-Down#111]

**Comment by PeterStaev** [comment]
@akshaydoiphode take a look at the readme there  are examples how to work with Value list items.

**Comment by akshaydoiphode** [comment]
yeah..i saw that. but in my scenario i am getting my drop down list from my
database..which is including of menu_id and menu name.. as dropdown concern
i have to push total list that why i am getting problem in iterating my
selected index menu_id and menu name.

**Comment by akshaydoiphode** [comment]
drop down in menucard.xml file is as
<dd:DropDown items="{{menuList}}" hint="Select Menu" id="drop" style="margin: 0 0 0 10;font-size:22;border-width:1.5;font-family: 'Roboto', Roboto;color:#009688;" width="320"    selectedIndex="{{ menu_idx }}" opened="dropDownOpened" selectedIndexChanged="onMenuChange" />
   

and i iterate my items by 
new Sqlite("KOTMASTER_db", function(err, db) {
            
            db.all('select menu_id,menu from menu_master', function(err, resultSet) {
            resultSet.forEach(function(row){
                viewModel.menuList.push(row[0]+' - '+row[1]);
               
               console.log("aaaaa"+viewModel.menu);
    });           
                
    so i am not getting values from this

**Comment by PeterStaev** [comment]
You need to transform your value and display members from the DB to the format of the `ValueList` class. There is no other way.
