### ISSUE TITLE
TNS 3 and 3.1: Border for DropDown element not being displayed

### ISSUE THREAD

**Issue by shivapersad** [PeterStaev/NativeScript-Drop-Down#112]
Good day,

I recently upgraded to {N}3.0.3 and then to {N}3.1. In {N}3.0.3 the border for a DropDown element I had in my mobile app is not being displayed. I upgraded to {N}3.1 and this issue is still occurring. I deleted the contents of my node_modules folder and performed "npm i" to have the latest version of the DropDown npm module. 

CSS code below:

Dropdown {

    width: 95%;
    height: 25%;
    color: #000000;
    margin-bottom: 7em;
    margin-left: 2.5%;
    margin-right: 2.5%;
    border-color: #97D700;
    background-color: #ffffff; /* white */
    border-width: 2em;
    text-align: center;
    font-weight: bold;

}

HTML code:

<Dropdown id="dd" #fuel [items]="fuels" [selectedIndex]="selectedFuelIndex" [hint]="hint"
        (selectedIndexChanged)="onChangeFuel(fuel.selectedIndex)" (opened)="openFuel()" [color]="color"></Dropdown>

Displayed on screen:
![image](https://user-images.githubusercontent.com/17012660/27703878-c67f88b0-5cd6-11e7-9791-7776d8076c0b.png)

Thanks for your assistance.

**Comment by shivapersad** [comment]
This issue seems to only be affecting the iOS version of the app. The Android version displays correctly.

**Comment by shivapersad** [comment]
Hi @PeterStaev, 
Any feedback on this? Were you able to reproduce the problem? Thanks.

**Comment by PeterStaev** [comment]
@shivapersad , this is probably but but I have not got the time to trace/fix it. As a workaround you can always wrap the widget in a layout and apply the border on the layout.
