### ISSUE TITLE
blank items

### ISSUE THREAD

**Issue by slasho** [PeterStaev/NativeScript-Drop-Down#115]
randomly I got blank items but when tap one blank item it shows OK, it goes random... not an specific bug....

I will post ans screenshot when this happend me again.

**Comment by PeterStaev** [comment]
@slasho , what version of the plugin you are using? There were problems in pre 3.1 version that should be resolved now.

**Comment by slasho** [comment]
```┌──────────────────┬─────────────────┬────────────────┬──────────────────┐
│ Component        │ Current version │ Latest version │ Information      │
│ nativescript     │ 2.5.4           │ 3.1.1          │ Update available │
│ tns-core-modules │ 2.5.2           │ 3.1.0          │ Update available │
│ tns-android      │ 3.0.1           │ 3.1.1          │ Update available │
│ tns-ios          │ 3.0.1           │ 3.1.0          │ Update available │
└──────────────────┴─────────────────┴────────────────┴──────────────────┘

Package                            Current  Wanted  Latest  Location
babel-traverse                      6.23.1  6.23.1  6.25.0
babel-types                         6.23.0  6.23.0  6.25.0
babylon                             6.16.1  6.16.1  6.17.4
nativescript-barcodescanner          2.5.0   2.6.0   2.6.0
nativescript-camera                  0.0.8   0.0.8   3.0.0
nativescript-checkbox                1.2.8   1.2.8   2.1.8
nativescript-dev-android-snapshot    0.0.8  0.0.10  0.0.10
nativescript-drawingpad              1.1.2   1.1.2   2.1.0
nativescript-drop-down               1.5.3   1.5.5   3.1.0
nativescript-geolocation            0.0.19  0.0.19   3.0.0
nativescript-imagepicker             2.5.2   2.5.2   3.0.1
nativescript-sqlite                  1.1.3   1.1.7   1.1.7
nativescript-theme-core              1.0.3   1.0.4   1.0.4


Can I update to 3.0.1 with NS 2.5.4??

**Comment by PeterStaev** [comment]
Your dependencies are not in sync. IN general it is not a good idea to use core modules version that is different than the runtime version of `tns-ios` and `tns-android` and it can cause problems. 

The 3.1 version of the plugin is only for TNS 3+ and you cannot use it with lower version of the core modules and runtime. But you can fork the report and then look at https://github.com/PeterStaev/NativeScript-Drop-Down/commit/b2da5b2ca2b086b3e5bc0697159f3028924b6d7c which resolves the invisible labels problem and then apply it to the older version of the plugin and rebuild it and use it in your project.

**Comment by slasho** [comment]
I did update to 1.5.5 and then delete de two lines 
 view.style.fontSize = 0;
view.style.padding = "0";

then did the:
tns platform remove android;
tns platform add android;

tns run android


but the  blank items remains .... any ideas?

**Comment by PeterStaev** [comment]
Have you synced your android and ios runtiime with the TNS core modules version?
