### ISSUE TITLE
Style drop down menu with CSS on Android

### ISSUE THREAD

**Issue by vcooley** [PeterStaev/NativeScript-Drop-Down#116]
It would be incredibly useful to have the ability to style the drop down separately from the spinner label. Currently, it is very frustrating to style the currently selected value as well as the drop down in a way that looks good for both. This is especially true when trying to align the selected value with other items in a form as changing padding or margin also changes those properties on the drop down.

If this is possible, I would suggest attaching a property that styles only the drop down, for instance `drop-down-class` or something of the sort.

If this is not possible, but there is a way to style the drop down natively, please point me in the right direction to be able to do that.

**Comment by PeterStaev** [comment]
Hey @vcooley , this is currently not possible you can see #44, and #21 . If you just want to apply padding/margin simply wrap it up with a `StackLayout` and apply the padding/margin there.
