### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by NicoleZA** [PeterStaev/NativeScript-Drop-Down#12]
I am not sure if there is a way.
But I cannot set font-size or padding on text-field

**Comment by dpdragnev** [comment]
@NikoleZA: did you manage to solve this issue?  I am facing the same problem.

**Comment by hchor** [comment]
:+1: Same here. This is main reason I can't use this right now, because it looks completely out of place with the rest of my UI. If I could programmatically control just the popup that would work as well.

**Comment by jeanonline** [comment]
Same here.

**Comment by PeterStaev** [comment]
The new version on npm adds much broader styling support.

**Comment by hchor** [comment]
:+1: Always appreciated

**Comment by kdmakwana43** [comment]
try this in css file
```

DropDown{
    font-size: 16;
    font-weight: bold;
}
```
