### ISSUE TITLE
Items in keyboard not visible in iOS when used with RadListView

### ISSUE THREAD

**Issue by simonox** [PeterStaev/NativeScript-Drop-Down#120]
OS: iOS
Environment: NativeScript: 3.1.2, Nativescript Telerik UI: 3.0.4
```
  "nativescript": {
    "id": "com.foo.bar",
    "tns-android": {
      "version": "3.1.1"
    },
    "tns-ios": {
      "version": "3.1.0"
    }
  }
```

I tried the sample code provided in the README. 

The selection is filled in Android (works!). 

![screenshot_20170726-121939](https://user-images.githubusercontent.com/117064/28616420-fa2f9ffc-71fc-11e7-8ca5-d310d4b2f0b9.png)

The keyboard is _empty_ in iOS (does not work).

![screen shot 2017-07-26 at 12 18 20](https://user-images.githubusercontent.com/117064/28616292-89806610-71fc-11e7-8215-7309b8de09a7.png)

**Comment by PeterStaev** [comment]
@simonox , please provide a sample or try to simulate this in the demo project as in the demo project things are working,

**Comment by simonox** [comment]
It happens if you are using a RadListView. I created an example: https://github.com/simonox/NativeScript-Drop-Down

**Comment by PeterStaev** [comment]
@simonox , since you have in the demo that it works with `ListView` but no with `RadListView` I suggest you submit an issue to the Telerik UI for TNS since this looks like a bug in the `RadListView` and/or something that blocks the binding of the drop down.

**Comment by simonox** [comment]
I submitted this Issue in Telerik UI: https://github.com/telerik/nativescript-ui-feedback/issues/259

**Comment by ginev** [comment]
@PeterStaev, @simonox: this has been addressed and is available through the early-build channel: nativescript-telerik-ui@next, nativescript-telerik-ui-pro@next.
