### ISSUE TITLE
How to fill a ValueList

### ISSUE THREAD

**Issue by magar91** [PeterStaev/NativeScript-Drop-Down#122]
Hi, I have a Service that provides with a list of objects from a server and I want to create a ValueList with that data how can I achieve that?
Thanks for the help. Regards

**Comment by PeterStaev** [comment]
Hey @magar91 , in the readme there is an example how you can fill in a `ValueList`.

**Comment by PeterStaev** [comment]
No further response so closing this one for now. In case you still have problems, please provide more details.
