### ISSUE TITLE
Dropdown list doesn't work on iOS

### ISSUE THREAD

**Issue by Yurrili** [PeterStaev/NativeScript-Drop-Down#123]
On android it works perfectly, but the same code doesn't work on iOS. it looks like normal label with no action after interacting with it. No error in logs as well.

I have installed version 3.0.3 of NativeScript and I'm running app on iPhone 4s emulator.

**Comment by PeterStaev** [comment]
Hey @Yurrili , is the error reproducable inside the demo project in this repo?

**Comment by Yurrili** [comment]
@PeterStaev Hey, I cannot run the demo due to error "We have failed to check if we need to add a compatability LaunchScreen.xib due to: Error: ENOENT: no such file or directory, open '/Users/fitech/Downloads/NativeScript-Drop-Down-master/app/App_Resources/iOS/Info.plist"

**Comment by PeterStaev** [comment]
I'm not sure I understand this error. The demo is a fully working project that you should be able to just clone and run. 

Alternatively can you provide a sample app that demonstrates the problem.

**Comment by Yurrili** [comment]
So this error "We have failed to check if we need to add a compatability LaunchScreen.xib due to: Error: ENOENT: no such file or directory, open '/NativeScript-Drop-Down-master/app/App_Resources/iOS/Info.plist" has shown after running command "tns run iOS" on newly downloaded demo.

Sample app is in this zip on dropbox: [Link](http://goo.gl/fp7L3X). It works perfectly on Android.

**Comment by PeterStaev** [comment]
I've just tried the application and for me it works ok - after tapping the drop down the list appears at the bottom:
![simulator screen shot aug 8 2017 12 34 22 pm](https://user-images.githubusercontent.com/9464097/29065959-76d96de2-7c36-11e7-99ae-2cfc1a4f79b3.png)

**Comment by Yurrili** [comment]
That's weird, for me it's not working at all. Im running it on emulator. But okay, anyway, thanks and sorry for bothering you.

**Comment by PeterStaev** [comment]
@Yurrili , the screenshot is from iPhone 4s sim running iOS 9.3. I suggest to delete your `node_modules` folder, run `npm install` and `tns platform clean ios` and try again.
