### ISSUE TITLE
Dropdown in iOs left aligned

### ISSUE THREAD

**Issue by Macarthurval** [PeterStaev/NativeScript-Drop-Down#124]
I don't know if this is the default behaviour, but in iOs the UIPickerView items are left aligned. I tried to fix this without success.

![simulator screen shot 08 08 2017 10 49 02 p m](https://user-images.githubusercontent.com/30457050/29104578-3604e7dc-7c8c-11e7-8e8f-fb23abbef10e.png)

However, in the image of the readme it appears centered. So, this is a bug, or I am missing something?

Thanks in advance.

**Comment by PeterStaev** [comment]
Hey @Macarthurval , this is per design. The items in the drop down follow the text alignment of the "label". If you want different alignments you will have to use the workaround mentioned here: https://github.com/PeterStaev/NativeScript-Drop-Down/issues/93#issuecomment-303311562
