### ISSUE TITLE
JS example

### ISSUE THREAD

**Issue by RobertoZgas** [PeterStaev/NativeScript-Drop-Down#125]
is there any js examples? cant make it work, keep getting error

**Comment by PeterStaev** [comment]
Hey @RobertoZgas , you can clone the repo and build the demo project. This will generate the JS files from the TS and you can examine those.

**Comment by RobertoZgas** [comment]
thank you for your reply. after trying everything i could i found out what was the problem. i dont know exactly what is the problem but the app crashes when i have a class named "page" on my page element, all that class does is this background-color: #fafeff;
after removing that class it works fine, i tried adding that class again and it crashes.
i have other classes on than element but the others dont cause problems so i guess it has to do with the background-color having conflicts with the dropdown plugin.
i added that property in-line like "style="background-color: #fafeff;"" and its working fine.
Thanks again.

**Comment by PeterStaev** [comment]
@RobertoZgas glad you have it sorted. The issue could be related to https://github.com/PeterStaev/NativeScript-Drop-Down/issues/109.
