### ISSUE TITLE
CSS Issue

### ISSUE THREAD

**Issue by ecolasurdo** [PeterStaev/NativeScript-Drop-Down#129]
I have the app.css with this line:
@import 'nativescript-theme-core/css/core.light.css';

And I see the dropdown with no style. What do I need to do to see it right?

**Comment by PeterStaev** [comment]
Hey @ecolasurdo , since the drop down is a 3rd party plugin it is not part of the default NatvieScript themes. So you will have to style it on your own so that it fits your screen designs and so that it fits the other styles of the theme you decided to use.

**Comment by ecolasurdo** [comment]
Thanks @PeterStaev. There's a default styling somewhere or a documentation? Because I couldn't find it. Thanks.

**Comment by PeterStaev** [comment]
There is no default styling or a document. You just apply whatever styles via inline or CSS/SCSS that fit your screen designs/theme.

**Comment by ecolasurdo** [comment]
But what are the objects? That's why I ask you for the documentation. Sorry, I know that is not about this repo.

**Comment by PeterStaev** [comment]
I'm not sure what do you mean with object. Here is some random style I apply in the demo project: https://github.com/PeterStaev/NativeScript-Drop-Down/blob/master/demo/app/app.css#L1

Simply use standard CSS properties as if you are styling a label. There is nothing special.

**Comment by ecolasurdo** [comment]
Thanks @PeterStaev
