### ISSUE TITLE
Arrow in Angular

### ISSUE THREAD

**Issue by Nurgunkalol** [PeterStaev/NativeScript-Drop-Down#130]
Hello, how to add arrow to open dropdown in angular ?

**Comment by PeterStaev** [comment]
Hey @Nurgunkalol , you can create a custom button that has an arrow image and combine that in a `GridLayout` together with the drop down. Then you can handle the tap event of the button and call the `open()` method of the drop down.

**Comment by PeterStaev** [comment]
No further response so closing this one for now. In case you still have problems, please provide more details.
