### ISSUE TITLE
CONSOLE ERROR when adding DropDownModule to import: []

### ISSUE THREAD

**Issue by fadiallos** [PeterStaev/NativeScript-Drop-Down#133]
Hi

I'm new to nativescript and angular.
Trying to use the nativescript plugin.
I've installed the plugin using tons plugin add nativescript-drop-down

When I add import { DropDownModule } from "nativescript-drop-down/angular"; and 
imports: [
        NativeScriptModule,
        DropDownModule,
        AppRoutingModule
    ],

My app produces a console error and all images stop rendering.

What am I doing wrong?

**Comment by PeterStaev** [comment]
Hey @fadiallos , it would be good if you provide the actual error... Also please refer to the demo-ng project in the repo and see how the drop down is set up there. You might be missing something in your implementation.

**Comment by fadiallos** [comment]
Thank you for coming back. I got it working by implementing it using registerElement.
