### ISSUE TITLE
Space out the dropdown Rows

### ISSUE THREAD

**Issue by DBhail** [PeterStaev/NativeScript-Drop-Down#140]
It would be nice to space the rows out on the dropdown selection ; not sure where to do this or what css to apply? Could you paste some cource code of how to do this please? The rows returned are very cramped

![image](https://user-images.githubusercontent.com/32709854/31486246-bc42db36-af2e-11e7-95c9-e88ea205be8a.png)

Also would be great to have a filter on the dropdown for really long lists?

**Comment by PeterStaev** [comment]
Hey @DBhail , you can simply apply `padding` via css and it should add spacing between the lines. Note that the padding is also applied to the text span as well. So you will might have to adjust your wrapping element as well. 

For the filter there is already #113

**Comment by DBhail** [comment]
The padding appears to apply to all or nothing !? Could you introduce a property specifically for padding out the rows in your next release. Because the rows are so close, you end up selecting the wrong value too often. Also would be nice to get rid of the underline which I haven't managed to work out yet.

**Comment by PeterStaev** [comment]
@DBhail as I explained it is applied to everything. Applying different styles will come in the future releases, just not sure it will be on the next one. 

For the underline I already explained to your comment how you can do it.
