### ISSUE TITLE
Deselect Row

### ISSUE THREAD

**Issue by DBhail** [PeterStaev/NativeScript-Drop-Down#141]
It would be really good if one could deselect a selected row/item. Consider a list of items which are optional. The user selects a value but then changes his mind and actually doesn't want to select an item at all. He cant select the hint as this is disabled (!?) although it is still displayed within the list and there is no other functionality to reset the drop-down.

**Comment by PeterStaev** [comment]
@DBhail , you can add a special button to clear the selection and in the handler set the bound property to `null`. Or add a "not selected" item to the list. For now I do not think adding ability to unselect an item fits in design principles (even on the web the drop down does not have ability to unmark items)
