### ISSUE TITLE
Does not Jump to selectedIndex

### ISSUE THREAD

**Issue by inviso** [PeterStaev/NativeScript-Drop-Down#144]
On IOS if I select a value from the dropdown, the selected item changes and everything seems fine.

If I change my mind and want to select another item, the scroll position on IOS is at the top again, even if I select e.g. the 10th element.

**Comment by PeterStaev** [comment]
Hey @inviso , I cannot reproduce this behavior with the demo app. For example i Select `Item 22`, then when I open the drop down again the list is correctly scrolled down to Item 22. Can you provide more details or attach a small sample app that reproduces the problem?

**Comment by PeterStaev** [comment]
No further response so closing this one for now. In case you still have problems, please provide more details.
