### ISSUE TITLE
Arrow change in Angular

### ISSUE THREAD

**Issue by BasyaLipman** [PeterStaev/NativeScript-Drop-Down#145]
How can I change the arrow to a customized icon in Angular?

Thanks!

**Comment by PeterStaev** [comment]
Hey @BasyaLipman , you should use a custom layout with a custom button which when tapped to call the `open()` method of the drop down.

**Comment by BasyaLipman** [comment]
Hi @PeterStaev - thanks for your response. Where can I find documentation on how to create a custom layout for the dropdown?

**Comment by PeterStaev** [comment]
There is no documentation, you just use standard layouts available in nativescript. For example (non-angular)
```xml
<GridLayout columns="*, auto">
    <dd:DropDown col="0" />
    <Button col="1" />
</GridLayout
```

**Comment by BasyaLipman** [comment]
@PeterStaev - then I would have two arrows. The dropdown already shows an arrow by default on my Android emulator...

**Comment by PeterStaev** [comment]
You can see #91 on how to hide the default arrow.
