### ISSUE TITLE
module not found: Error: Can't resolve 'nativescript-angular/forms/value-accessor

### ISSUE THREAD

**Issue by spmamidi** [PeterStaev/NativeScript-Drop-Down#147]
Getting following error when building with webpack.

Module not found: Error: Can't resolve 'nativescript-angular/forms/value-accessors/base-value-accessor' in 'c:\test\node_modules\nativescript-drop-down\angular'

**Comment by PeterStaev** [comment]
Hey @spmamidi , new version of the plugin (3.2) required Angular 4.4. So you will either have to upgrade your deps or you will have to use the previous one.

**Comment by faspadaro** [comment]
Hey @PeterStaev, I have upgrade to Angular 4.4 but there is the  component nativescript-checkbox that does not work any more.

**Comment by PeterStaev** [comment]
Well you should submit an issue to the plugin site, or downgrade to the 3.1.3 version until all plugins support Angular 4.4.

**Comment by jogboms** [comment]
@faspadaro the issue has been resolved [here](https://github.com/bradmartin/nativescript-checkbox/pull/66) but pending a MERGE from the author.

**Comment by sivamamidi-REISys** [comment]
Thank you we pointed out 3.1.3 it's working fine.
