### ISSUE TITLE
Question; Select Itme by Display value

### ISSUE THREAD

**Issue by markomiljkovic** [PeterStaev/NativeScript-Drop-Down#148]
Hello guys I have one quick question ,
How can I get Index of my item based on its Display value not by getIndex();

**Comment by PeterStaev** [comment]
Hey @markomiljkovic , this is not supported out of the box. So you will have to implement your own custom logic if you want to do it.

**Comment by markomiljkovic** [comment]
Ok thanx for fast answer :)
