### ISSUE TITLE
Problems with isEnabled and ngModel

### ISSUE THREAD

**Issue by wendt88** [PeterStaev/NativeScript-Drop-Down#152]
1) `ERROR Error: java.lang.Exception: Failed resolving method setEnabled on class android.widget.Spinner` -> items are a ValueList

```
<DropDown #dd
            [hint]="'application' | L"
            [items]="items"
            [(ngModel)]="itemIndex"
            (selectedIndexChanged)="itemSelect($event)"
            [isEnabled]="items.length"></DropDown>
```

2) `ERROR Error: No value accessor for form control with unspecified name attribute` -> only if my `ValueList` is empty (I fetch the items for the `ValueList` via api call, so I get this error and no `[text]` or `[hint]` attributes in the whole page get evaluated until I fill my `ValueList`).
**Removing `[(ngModel)]` solves the problem!**

I tried to set as `itemIndex` various initial values (null, undefined, 0, etc)

**Comment by PeterStaev** [comment]
Hey @wendt88 , 
For 1 - this is a really strange error. `setEnabled` is a valid method for the spinner per the [android docs](https://developer.android.com/reference/android/widget/Spinner.html). 

For 2 - Make sure you are using the module as explained in the readme. Also you might have to initialize the `items` property  and probably use the angular `async` pipe with it since you are retrieving the data with an API call.

**Comment by wendt88** [comment]
For 2 - I initialize my items in `ngOnInit` as a empty `ValueList` and call on api request end multiple times the push method to write the items in it. I resolved it adding the `ngDefaultControl` attribute [found here](https://stackoverflow.com/questions/38978166/no-value-accessor-for-form-control-with-name-recipient)
But now my `itemIndex` get not changed on select (`selectedIndexChanged` event gets called)

TextFields with [(ngModel)] works fine.

I use:
```
@angular: "~4.4.5"
nativescript-drop-down: "^3.2.0"
tns-core-modules: "~3.2.0"
```

**Comment by PeterStaev** [comment]
How are you registering the module? You should not use `ngDefaultControl` and the widget already implements its own value accessor.

**Comment by wendt88** [comment]
I started with the [NativeScript/sample-Groceries](https://github.com/NativeScript/sample-Groceries) repository

and imported the `DropDownModule` in the [app.module.ts](https://github.com/NativeScript/sample-Groceries/blob/master/app/app.module.ts).

The drop is in my login component which is declared in the [login.module.ts](https://github.com/NativeScript/sample-Groceries/blob/master/app/login/login.module.ts)

**Comment by PeterStaev** [comment]
I'm not sure what could be wrong. I would suggest to look at the `demo-ng` project in this repo and see what you are doing differently in your project so you can isolate what the problem is.

**Comment by wendt88** [comment]
Problem solved:
I have to import the `DropDownModule` in the submodule (in groceries sample is it the `LoginModule` and `GrocieruesModule`) instead of the `AppModule`.

Now I created my own "`SharedModule`", where I import the `DropDownModule` (here you can also declare your own pipes, services, components etc. if somene is interested) and export everything of it.

Thank you for your help!
