### ISSUE TITLE
Space between arrow and text

### ISSUE THREAD

**Issue by markomiljkovic** [PeterStaev/NativeScript-Drop-Down#153]
Hello guys, I have a quick question
is it possible to make space smaller between 
dropdown arrow and text in dropdown ????

**Comment by PeterStaev** [comment]
Hey @markomiljkovic , what you see is the default spacing that comes with android (unless you have applied some padding on the elements). So if you want to decrease spacing you will have to add your own arrow and then position it accordingly.

**Comment by markomiljkovic** [comment]
ok, but how can I add my own arrow and position it, 
sorry Im a little new to this :)
