### ISSUE TITLE
Customize ValueList object with custom key/value

### ISSUE THREAD

**Issue by relvis** [PeterStaev/NativeScript-Drop-Down#154]
Hey there, we have an existing API that is working with current apps and we use ID/Description as key/value pair, is there any way to customize the ValueList object key/value?

Thanks!

**Comment by PeterStaev** [comment]
Hey @relvis , there is no customization but it is not needed as you can simply remap them in TS/JS.

**Comment by relvis** [comment]
For documentation purposes should look like this, correct me if I am wrong @PeterStaev:

```
var mappedItems = originalArray.map(item => ({
   display: item.Description,
    value: item.ID
}));
```

Thanks!
