### ISSUE TITLE
Is it Possible to Select Multiple Index at Once from the DropDown Items?

### ISSUE THREAD

**Issue by ahtishamashraf** [PeterStaev/NativeScript-Drop-Down#155]
I wish to know if the Dropdown Allows us to Select Multiple SelectedIndex from the Items in DropDown

**Comment by PeterStaev** [comment]
Hey @ahtishamashraf , selecting multiple items is not available in this plugin. Also I think it does not fit in the design of the plugin and is more suitable for a new plugin.
