### ISSUE TITLE
Dropdown arrow not visible on IOS

### ISSUE THREAD

**Issue by markomiljkovic** [PeterStaev/NativeScript-Drop-Down#159]
Hello Im having issue on my android the dropdown arrow is visible,
but on my Ios device ????

**Comment by PeterStaev** [comment]
Hey @markomiljkovic , there is no arrow for iOS since this is how native control looks like. If you want you can add an arrow by adding a the drop down and a button with the arrow icon in a `GridLayout` and then handling the `tap` event of the button and call the `open()` method of the drop down.

**Comment by PeterStaev** [comment]
No further response so closing this one for now. In case you still have problems, please provide more details.
