### ISSUE TITLE
Dropdown items take too much space

### ISSUE THREAD

**Issue by markomiljkovic** [PeterStaev/NativeScript-Drop-Down#160]
I have a question:
Why do dropdown items take space of the longest string in inputs???
My Code sample:
<dd:DropDown  items="{{ states }}"
                           class="ab_dropdown_r"
                           hint="" selectedIndex="{{ statesSelectedIndex }}"
                           opened="dropDownOpened" closed="dropDownClosed"
                           selectedIndexChanged="dropDownSelectedIndexChanged"/>

.ab_dropdown_r {
    vertical-align: center;
    horizontal-align: right;
    padding: 5;
}

**Comment by PeterStaev** [comment]
@markomiljkovic , I do not understand what do you mean with "take space of the longest inputs". Please provide more details, screenshots and what are you trying to achieve.

**Comment by markomiljkovic** [comment]
Never mind, the issue was at my side with GridLayout..
You can close, thanx for fast response :)
