### ISSUE TITLE
Dropdown is not working correctly

### ISSUE THREAD

**Issue by bnbs** [PeterStaev/NativeScript-Drop-Down#163]
As you can see from the gif below, the dropdown behavior is really strange. Just when I selected one item the dropdown started working correctly. After a few test I found out that the problem seems to happen only when I use selectIndex = null;
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22986188/36222080-4be445b0-11a7-11e8-80b7-3e8f20fa9c0d.gif)

**Comment by PeterStaev** [comment]
Hey @bnbs , is your app Angular based, or plain NatvieScript?

**Comment by bnbs** [comment]
Angular + NativeScript

**Comment by PeterStaev** [comment]
Ok, there is a problem with the plugin specifically for Angular when used inside a tabview (#157). Sadly I have no ETA on when the problem is going to be fixed.
