### ISSUE TITLE
seelectedindexchange not working when drop down is collapsed on android.

### ISSUE THREAD

**Issue by giorgi-abashidze** [PeterStaev/NativeScript-Drop-Down#165]
how to get selectedindexchange on android when drop down is collapsed? i hided it because I'm opening dropdown from other element tap event.

**Comment by PeterStaev** [comment]
The plugin is not meant to be used in such a "hacky" way. So I have no idea why the event it not triggered and how should you handle this problem. I suggest you use the plugin in a normal way and styling it to match your current design.

**Comment by giorgi-abashidze** [comment]
ok than, if its possible to align text left on trigger but align text center inside dropdown window?

**Comment by PeterStaev** [comment]
This will be added with #142

**Comment by giorgi-abashidze** [comment]
when will be available 142?

**Comment by PeterStaev** [comment]
Sadly I can't give you any ETA. Also currently the way to style child elements of the plugin is a bit tricky and could be changed in a future release due to a submitted issue on the nativescript repo.

**Comment by giorgi-abashidze** [comment]
@PeterStaev i tried to edit code but there is no comments and idk what i'm doin :/ what is difference between trigger and drop down or spinner? realizedViewType? I want to separate them and hardcode colors 
and textAlignment

**Comment by giorgi-abashidze** [comment]
@PeterStaev I did it for android ! 🥇  now how about ios? there is no realizedViewType
