### ISSUE TITLE
Dropdown always auto changed to index +4 after click 'done' or click outside dropdown view

### ISSUE THREAD

**Issue by bamz3r** [PeterStaev/NativeScript-Drop-Down#166]
Just run demo apps in ios emulator .
```
$ git clone https://github.com/peterstaev/nativescript-drop-down
$ cd nativescript-drop-down
$ npm install
$ npm run demo-ios
```
Nativescript 3.4.0
All npm package already latest version (checked with 'npm outdate')
Xcode 9
Mac OS High Sierra 10.13.1

**Comment by PeterStaev** [comment]
I don't see such a behavior. Make sure you have not made any changes and/or you typed `4` in the selected index textbox under the drop down.

**Comment by bamz3r** [comment]
Sorry, after tested on another emulator version (iPhone 6 iOS 10.3) and real android device, work perfectly. So, It appear only in ios emulator iPhone 5s iOS 11.2. It seem related to ios emulator bug, or something compabillity issue with newest iOS version.
