### ISSUE TITLE
Is it possible to show changed color of selected option when dropdown is clicked?

### ISSUE THREAD

**Issue by ejaz** [PeterStaev/NativeScript-Drop-Down#167]
![page 3](https://user-images.githubusercontent.com/310490/36836792-2ba31572-1d5c-11e8-9ea9-d87d11bc0aea.png)
Is it possible to show changed color of selected option when dropdown is clicked? Please see above picture for requirement. thanks in advance. :)

**Comment by PeterStaev** [comment]
This will be coming with #142 . Currently I don't have an ETA on this.
