### ISSUE TITLE
IOS showing dropdown arrow

### ISSUE THREAD

**Issue by markomiljkovic** [PeterStaev/NativeScript-Drop-Down#168]
Hello guys,
I have looked on forums and stackoverflow but couldnt find answer..
My question is how can I add dropdwon arrow icon on IOS ( I know there is no arrow for iOS since this is how native control looks like ),
but I would like to add it so, how can I do ?? 
Could your provide me some sample code, since Im new to all this ??

**Comment by PeterStaev** [comment]
Hey @markomiljkovic , I've already answered your question here: https://github.com/PeterStaev/NativeScript-Drop-Down/issues/159#issuecomment-359925215. So you need to add your own button with the arrow image and then when tapped to call the `open()` method.
