### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by dpdragnev** [PeterStaev/NativeScript-Drop-Down#17]
Hello,

Is there a way to style the look of the selected value?  I tried applying css classes and also inline styles, but nothing worked.

I saw a closed ticket that indicates that this is possible, but in my case, it does not work. I am developing for iOS using version 1.2.5.  I am defining the drop down like this:

`<dd:DropDown items="{{ accountTypes }}" selectedIndex="{{ customer.AccountType }}" class="ddl" />
.ddl {
    font-size: 10;
    color: #a8b4b9;
    font-weight: bold;
}`

Thank you.

**Comment by PeterStaev** [comment]
Hey @dpdragnev , currently there are very few styling options. More will be added with #12.
