### ISSUE TITLE
Aligment and Auto-resize dropdown

### ISSUE THREAD

**Issue by markomiljkovic** [PeterStaev/NativeScript-Drop-Down#173]
Hello guys I have code here:
```
<GridLayout columns="*,200">
             <GridLayout   col="1"  columns="40,*,auto" class="right">
                <Label col="0" class="ab_headline_num" text="Length"  />
                <dd:DropDown col="1" id="filter-dd" color="black" items="{{ states }}"
                             selectedIndex="{{ index }}"
                             opened="dropDownOpened" closed="dropDownClosed"
                             selectedIndexChanged="dropDownSelectedIndexChanged"/>
                <Label col='2' class='ab_dropdown-arrow' style="color: #8F8F8F;" text="&#xf0d7;" />
             </GridLayout>
        </GridLayout>
```
`
state = ['test', 'teśssssssssssssssssssss', 'test2'];`
I would like GridLayout with class 'right' to ove to the right edge of the screen, and the items in dropdown to auto resize based on the length of text, how can I do this on IOS???

**Comment by PeterStaev** [comment]
@markomiljkovic I do not understand what you want to achieve. If you want to right align the text in the drop down then you need to apply `text-align: right` to the drop down style.

**Comment by PeterStaev** [comment]
No further response so closing this one for now. In case you still have problems, please provide more details.
