### ISSUE TITLE
Nativescript WebPack  java.io.IOException: File already exists

### ISSUE THREAD

**Issue by alexma01** [PeterStaev/NativeScript-Drop-Down#175]
Hi guys,
I have 3 classes defined this way:

`@JavaProxy("com.tns.notifications.TestProxy")
  class Test extends com.google.firebase.iid.FirebaseInstanceIdService {
    onTokenRefresh(){
       ...
        }
    }
 }`

when I build with **tns build android --bundle** i have this error:

**Exception in thread "main" java.io.IOException: File already exists. This may lead to undesired behavior.
Please change the name of one of the extended classes.
File:/----/platforms/android/app/src/main/java/com/tns/notifications/Test.java Class: com.tns.notifications.TestProxy**

tns --version   ==> 4.1.0-2018-04-18-11407

{
  "description": "",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "***",
    "hooks": [
      {
        "type": "before-prepare",
        "script": "app.entitlements.js"
      },
      {
        "type": "before-prepare",
        "script": "build-gradle-template.js"
      },
      {
        "type": "before-prepare",
        "script": "copy-google-services.js"
      }
    ],
    "tns-android": {
      "version": "4.1.0-2018.4.18.2"
    },
    "tns-ios": {
      "version": "4.0.2-2018-04-18-01"
    }
  },
  "dependencies": {
    "@angular/animations": "~5.0.0",
    "@angular/common": "~5.0.0",
    "@angular/compiler": "~5.0.0",
    "@angular/core": "~5.0.0",
    "@angular/forms": "~5.0.0",
    "@angular/http": "~5.0.0",
    "@angular/platform-browser": "~5.0.0",
    "@angular/platform-browser-dynamic": "~5.0.0",
    "@angular/router": "~5.0.0",
    "angular2-jwt": "^0.2.3",
    "angular2-moment": "^1.8.0",
    "base-64": "^0.1.0",
    "buffer": "^5.0.8",
    "file-system": "^2.2.2",
    "http": "0.0.0",
    "moment-timezone": "^0.5.14",
    "nativescript-angular": "^5.0.0",
    "nativescript-background-http": "^3.1.0",
    "nativescript-camera": "^4.0.2",
    "nativescript-carousel": "^3.1.1",
    "nativescript-checkbox": "^3.0.3",
    "nativescript-drop-down": "^3.2.1",
    "nativescript-geolocation": "^4.2.3",
    "nativescript-google-maps-sdk": "^2.6.0",
    "nativescript-image-cache": "^1.1.6",
    "nativescript-imagepicker": "^5.0.2",
    "nativescript-iqkeyboardmanager": "^1.3.0",
    "nativescript-linearprogressbar-elica": "^1.0.0",
    "nativescript-localize": "^2.1.0",
    "nativescript-localstorage": "^1.1.5",
    "nativescript-mediafilepicker": "^1.0.5",
    "nativescript-number-progressbar": "^1.0.0",
    "nativescript-orientation": "^2.2.0",
    "nativescript-phone": "^1.3.1",
    "nativescript-photoviewer": "^1.4.0",
    "nativescript-pulltorefresh": "^2.1.0",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-ui-chart": "^3.5.0",
    "nativescript-ui-listview": "^3.5.1",
    "ng2-translate": "^5.0.0",
    "path": "^0.12.7",
    "reflect-metadata": "~0.1.8",
    "rxjs": "^5.5.0",
    "tns-core-modules": "^4.0.0",
    "utf8": "^3.0.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~5.0.0",
    "@ngtools/webpack": "~1.8.2",
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "copy-webpack-plugin": "~4.0.1",
    "css-loader": "~0.28.7",
    "extract-text-webpack-plugin": "~3.0.0",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.7.1",
    "nativescript-dev-webpack": "^0.9.0",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.1.0",
    "tns-platform-declarations": "^3.4.1",
    "typescript": "~2.4.2",
    "webpack": "~3.8.1",
    "webpack-bundle-analyzer": "^2.8.2",
    "webpack-sources": "~1.0.1"
  }
}

Thanks all

**Comment by PeterStaev** [comment]
Hey @alexma01 , I do not understand how this related to the DropDown widget?

**Comment by alexma01** [comment]
sorry, delete post. My bad
