### ISSUE TITLE
selected row is not a selected index

### ISSUE THREAD

**Issue by giorgi-abashidze** [PeterStaev/NativeScript-Drop-Down#178]
while i am on the page and pick one item from picker and close it and then open picker again it have focus "selectedRow" on picked item, not on the first item. but when i go to another page and go back
and open picker again, the selected row is first item while i did have set selected index on selected item for example the second item, trigger is showing the selected item with my selectedIndex

**Comment by PeterStaev** [comment]
Hey @giorgi-abashidze , I cannot simulate this behavior. Here is playground with the testbed I used:
https://play.nativescript.org/?template=play-tsc&id=20jgHf

Can you please provide a playground (or sample app) where this problem is reproducible?

**Comment by giorgi-abashidze** [comment]
are you testing it on android or ios? I have this problem on ios

**Comment by PeterStaev** [comment]
iOS (don't have any hardware android devices)

**Comment by giorgi-abashidze** [comment]
i will test your playground tomorrow, now I don't have ios device

**Comment by simonox** [comment]
Same with me. But in the playground this issue is not reproducible (at the moment). I am trying to provide a test case where this issue is reproducible.
