### ISSUE TITLE
How can I use this in nativescript-vue?

### ISSUE THREAD

**Issue by starryalley** [PeterStaev/NativeScript-Drop-Down#180]
My environment is nativescript-vue with typescript. 

I tried the following in my main.ts:
`Vue.registerElement("DropDown", () => require("nativescript-drop-down/drop-down").DropDown);`

And then using the DropDown tag in a component.vue file like this:

```
<template>
    <StackLayout>
        ...
        <DropDown :items="myitems" selectedIndex="0" />
        ...
    </StackLayout>
</template>
```

Unfortunately it just hangs there without any message. Commenting out the DropDown line then it renders fine. 

I followed this guide to use nativescript plugin:
https://www.nativescript.org/blog/using-plugins-in-a-nativescript-vue-app

Any ideas? Thank you.

**Comment by PeterStaev** [comment]
Hey @starryalley , I have no clue about Vue so can't help you on this. My guess is that the plugin requires a its own Vue thingy just like for Angular and cannot be used out of the box. But I do not have any current plans of adding Vue support. But will accept and merge any PR that wants to add Vue support 😉

**Comment by starryalley** [comment]
Thanks @PeterStaev. I'm also very new to nativescript-vue. I'll try and see if I can make it work. If so I'll send a PR!

**Comment by msaelices** [comment]
@PeterStaev I just did the same steps than @starryalley and it's working like a charm.

**Comment by starryalley** [comment]
@msaelices I really want to know how you set it up? 

Are you also using nativescript-vue with typescript in <script lang="ts> tag, with single file vue component? Thanks.

**Comment by msaelices** [comment]
Basically I tested it only on Android. Now I've tested it on iOS and I get the silent error you got ;)

**Comment by starryalley** [comment]
Thanks for confirming. I worked on iOS as well. Haven't tested on Android.

**Comment by msaelices** [comment]
@starryalley I think I've got the error cause. It's related to webpack, which bundle the DropDown code as well as putting into node_modules. So there are several references of DropDown and NS thinks is not a View subclass. I will send a fix for that.

**Comment by starryalley** [comment]
Great news. I know nothing about webpack. Thanks. I'll definitely give your fix a try when it's there.

**Comment by msaelices** [comment]
After several hours debugging. I finally fix the problem installing the latest NPM packages.

**Comment by dwatring** [comment]
@msaelices Can you be more specific with your fix? Thanks!

**Comment by msaelices** [comment]
@dwatring sure, these are my dependencies (placed on `template/package.json`):

```
"dependencies": {
    "nativescript-drop-down": "^4.0.0",
    "nativescript-email": "^1.5.2",
    "nativescript-permissions": "^1.2.3",
    "nativescript-phone": "^1.3.1",
    "nativescript-push-notifications": "^1.1.3",
    "nativescript-telephony": "^1.0.4",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-vue": "^1.4.0-alpha.0",
    "tns-core-modules": "^4.1.0",
    "vue-router": "^3.0.1"
  },
```

**Comment by starryalley** [comment]
It turns out the package.json in template isn't get updated in my setup. With nativescript-vue@1.3.1 and tns-core-modules@4.1.0 this works perfectly fine on iOS. Closing.

**Comment by wendt88** [comment]
Thx for your implementation!
Can I use `v-model="selectedIndex"` or should I work with `:selectedIndex="selectedIndex"` and `@selectedIndexChanged="selectedIndexChanged"` to handle the value?

On init I would set the first value of my `items` so I tried:
```
created () {
        this.$set(this, 'selectedIndex', 0);
}
```
But I am not able to set a value from outside
