### ISSUE TITLE
No value accessor for form control with unspecified name attribute

### ISSUE THREAD

**Issue by artdias90** [PeterStaev/NativeScript-Drop-Down#182]
```
"@angular/common": "~6.0.0",
"nativescript-drop-down": "^4.0.0",
```

I followed the demo-angular both html and .ts, but I keep getting this error  `No value accessor for form control with unspecified name attribute`.
Dropdown works but the error appears when I emulate on iOS.

Also after adding `name=test` I get `No value accessor for form control with name:`

`tns run ios`

```
CONSOLE ERROR [native code]: ERROR Error: No value accessor for form control with unspecified name attribute
CONSOLE ERROR [native code]: ERROR CONTEXT {
"view": {
"def": {
"nodeFlags": 403326993,
"rootNodeFlags": 402653185,
"nodeMatchedQueries": 2,
"flags": 0,
"nodes": [
{
"nodeIndex": 0,
"parent": null,
"renderParent": null,
"bindingIndex": 0,
"outputIndex": 0,
"checkIndex": -1,
"flags": 402653184,
"childFlags": 0,
"directChildFlags": 0,
"childMatchedQueries": 0,
"ngContentIndex": -1,
"matchedQueries": {},
"matchedQueryIds": 0,
"references": {},
"childCount": 0,
"bindings": [],
"bindingFlags": 0,
"outputs": [],
"element": null,
"provider": null,
"text": null,
"query": {
"id": 1,
"filterId": 2,
"bindings": [
{
"propName": "dd",
"bindingType": 0
}
]
```

**Comment by PeterStaev** [comment]
Hey @artdias90 , I've just updated the deps on the demo project and I cannot simulate this behavior. Make sure you are registering the drop down module like in the demo app/readme. If you still experience the problem, provide a reproducible sample either in the playground or attaching it here.

**Comment by artdias90** [comment]
Thanks for checking. Your demo works for me as well, I will try it further with my setup here.

**Comment by artdias90** [comment]
FYI I removed `[class]="cssClass"`  and it fixed the problem for me.
```
<DropDown #dd
      [items]="items"
      [(ngModel)]="selectedIndex"
      [hint]="hint"
      (selectedIndexChanged)="onchange($event)"
      (tap)="change()"></DropDown>
```
