### ISSUE TITLE
Cannot get it to work in  nativescript-vue..

### ISSUE THREAD

**Issue by Peraluna** [PeterStaev/NativeScript-Drop-Down#184]
Is it possible to use this DropDown element in nativescript-vue ? If so, could you please show how to use it ? 
I've tried to register it using : 
 Vue.registerElement("DropDown", () => require("nativescript-drop-down").DropDown) in main.js 

But when I use it in my vue component file using <DropDown> tag, I got error :  
JS: [Vue warn]: Error in nextTick: "TypeError: Could not load view for: dropdown. TypeError: view_1.CSSType is not a function"

**Comment by PeterStaev** [comment]
The search is your friend: https://github.com/PeterStaev/NativeScript-Drop-Down/issues/180
