### ISSUE TITLE
how to add dropdown field in nativecsript view for ios 

### ISSUE THREAD

**Issue by kanchanagarwal3** [PeterStaev/NativeScript-Drop-Down#188]
tried using nativescript-drop-down plugin but it adds button which opens up all the items.
Is it possible to have a dropdown just like we get in simple HTML file

Naviscript version - 4.1.2

**Comment by PeterStaev** [comment]
This widget uses the native controls that are used to display list of values. If you open in Safari a page that has a drop down in it, you will see that the visual will be the same, and this is the recommended behavior. So no you cannot have it work like an HTML `select` control running on a desktop.

**Comment by kanchanagarwal3** [comment]
i am trying to run in nativescript mobile app

**Comment by PeterStaev** [comment]
I know, my comment still applies - this widget uses the default (and recommended) way of showing list of items. And those do not show items like a `select` control in an html web site displayed on a desktop browser. So if you have a requirement the UI to look like a web drop down, then you can't use this plugin and you have to find another one, or implement one yourself.

**Comment by kanchanagarwal3** [comment]
ok thanks for the explanation
