### ISSUE TITLE
Clear selected index / reset

### ISSUE THREAD

**Issue by xjpmauricio** [PeterStaev/NativeScript-Drop-Down#189]
Is there a way to clear the selected index of the dropdown or somehow reset it to it's initial state?

**Comment by PeterStaev** [comment]
Hey @xjpmauricio , have you tried the `selectedIndex` property to `null`?

**Comment by xjpmauricio** [comment]
Ok i'll try it.

**Comment by xjpmauricio** [comment]
It works, thanks.

**Comment by xjpmauricio** [comment]
It works, thanks.
