### ISSUE TITLE
Aligning label text independently

### ISSUE THREAD

**Issue by meysam-mahmoodi** [PeterStaev/NativeScript-Drop-Down#194]
I'd like to align label text, independent of drop-down text. Actually I'd like to align label to left and remain drop down text to center.
Is there a way to do that?
thanks

**Comment by PeterStaev** [comment]
Hey @meysam-mahmoodi , this is currently not possible with the plugin. You can track #142 for when this becomes available. For iOS you can check this comment: https://github.com/PeterStaev/NativeScript-Drop-Down/issues/93#issuecomment-303311562 for a temporary workaround.
