### ISSUE TITLE
Wrong selected value when clicking the "Done" button on ios

### ISSUE THREAD

**Issue by websmurf** [PeterStaev/NativeScript-Drop-Down#196]
I noticed an issue with the selected value in my VueJS project today, after some investigation it goes wrong in the demo you have available as well. 

*Reproduction steps*:
```
$ git clone https://github.com/peterstaev/nativescript-drop-down
$ cd nativescript-drop-down
$ npm install
$ npm run demo-ios
```

Click on the big red bar, select "Item 1", notice that the bar changes correctly.
After clicking the "Done" button, the selected option jumps to "Item 5" all of a sudden.

A visual reproduction can be found here: http://recordit.co/O1mcRGYJka

**Comment by websmurf** [comment]
Note, this goes for the other options as well. 
So selecting "Item 2" means that "Item 6" will be selected once the "Done" button is clicked etc.

**Comment by PeterStaev** [comment]
Hey @websmurf , I've just updated the demo app to the latest version of NativeScript (5.2.2) and I do not see this behavior. Can you provide more details?

**Comment by PeterStaev** [comment]
No further response so closing this one for now. In case you still have problems, please provide more details.
