### ISSUE TITLE
Creating dd element on the fly

### ISSUE THREAD

**Issue by des-esseintes** [PeterStaev/NativeScript-Drop-Down#199]
Hello,
is it possible to create an element in js, not in xml? Like, const dd = new DropDown() and so on.
Could not find answer to this question.
Thanks!

**Comment by PeterStaev** [comment]
Hey @des-esseintes , there should be no problem to create the element in code, just like any other NativeScript widget. After all Nativescript creates the objects from the XML 😉

**Comment by des-esseintes** [comment]
Yeah I understand, haha, but cant find the api reference, sorry. Any example, maybe? Thank you!

**Comment by PeterStaev** [comment]
The API is not much different than what you would do with the built in widgets. So you should be able to adapt the examples there are in the NativeScript docs (for example [this one](https://docs.nativescript.org/ui/basics#code-only-custom-component)) so they work with the drop down. 
If you need further assistance our company offers paid support for all of the plugins we have built: https://www.tangrainc.com/subscriptions/

**Comment by des-esseintes** [comment]
thanks, will try that.
would be cool if the documentation contained api reference, though.
