### ISSUE TITLE
Getting the value of selecting item onchange.

### ISSUE THREAD

**Issue by imranrafiq01** [PeterStaev/NativeScript-Drop-Down#2]
I want to get the value or let say 'id' of the item that I select from dropdown. I've tried using onPropertyChange method of nativescript but this doesn't fulfill what I want. Every time I select any item it returns me the index position of that item. Any idea how can I get the text or other details of the selected item like we do in jquery's onchange function.

**Comment by PeterStaev** [comment]
@imranrafiq01 , since the **items** property can be set to a JS array or JS object that implements a `getItem(index: number)` function (for example an ObservableArray) you can implement a custom class that suits your needs. For example the one I'm using in my application looks like this:

```typescript
export interface IValueItem
{
    ValueMember: any
    DisplayMember: any
}

export class ValueList
{
    private _array: Array<IValueItem>;

    get length(): number { return this._array.length; }

    constructor(array: Array<IValueItem>)
    {
        this._array = array;
    }

    public getItem(index: number) // Used for items source in list picker
    {
        return this.getText(index);
    }

    public getText(index: number): string
    {
        if (index < 0
            || index >= this._array.length
            )
        {
            return "";
        }

        return this._array[index].DisplayMember;
    }

    public getValue(index: number)
    {
        if (index < 0
            || index >= this._array.length
            )
        {
            return null;
        }

        return this._array[index].ValueMember;
    }

    public getIndex(value: any): number
    {
        var loop: number;

        for (loop = 0; loop < this._array.length; loop++)
        {
            if (this.getValue(loop) == value)
            {
                return loop;
            }
        }
        
        return -1;
    }
}
```

This enables you to do the following:
```typescript
var itemsSource = new ValueList([{ValueMember: "A", DisplayMember:"Test1"}, {ValueMember: "B", DisplayMember:"Test2"}]);

var x = itemsSource.getValue(0); // x = "A"
var y = itemsSource.getIndex("B"); // y = 1
```

You should be able to adjust this to suite the needs of your application. Hope this helps.

**Comment by imranrafiq01** [comment]
Thanks @PeterStaev for your quick response. you've, if i'm not wrong, done this using typescript, right? Is there any way to achieve this in nativescript? I've tried the nativescript's event handler (onPropertyChange) but it's not working fine for me.

**Comment by PeterStaev** [comment]
@imranrafiq01 nativescript uses typescript/javascript as a backend. Here is the JS compiled ValueList class which you should be able to use (the second code snippet i gave above is the same for JS/TypeScript):

```javascript
var ValueList = (function () {
    function ValueList(array) {
        this._array = array;
    }
    Object.defineProperty(ValueList.prototype, "length", {
        get: function () { return this._array.length; },
        enumerable: true,
        configurable: true
    });
    ValueList.prototype.getItem = function (index) {
        return this.getText(index);
    };
    ValueList.prototype.getText = function (index) {
        if (index < 0
            || index >= this._array.length) {
            return "";
        }
        return this._array[index].DisplayMember;
    };
    ValueList.prototype.getValue = function (index) {
        if (index < 0
            || index >= this._array.length) {
            return null;
        }
        return this._array[index].ValueMember;
    };
    ValueList.prototype.getIndex = function (value) {
        var loop;
        for (loop = 0; loop < this._array.length; loop++) {
            if (this.getValue(loop) == value) {
                return loop;
            }
        }
        return -1;
    };
    return ValueList;
})();
```

**Comment by Jayuda** [comment]
Hello @imranrafiq01, how to get selected items ?
i have use    

```
var pageArg = <pages.Page>args.object;
var  comboOutlets = viewModule.getViewById(pageArg, "comboOutlets");
console.log(comboOutlets.text)
```

Not show anything.

what shoud the code to get value of selected dropdown.

**Comment by PeterStaev** [comment]
Hey @Jayuda , in order to get the selection you need to use the `selectedIndex` property and then pull the value from whatever you set to the `items` property of the widget. Basically working with the DropDown widget is similar to how you work with the {N} [ListPicker widget](https://docs.nativescript.org/ApiReference/ui/list-picker/HOW-TO.html).

**Comment by Jayuda** [comment]
Hello Mr. @PeterStaev ,
i have done with this this step : 
1. I save to localsettings ` appSettings.setString("outlets", JSON.stringify(data)) `on set dropdown items;
2. On selected items, i get index with selectedIndex : `comboOutlets.get("selectedIndex")`
3. `var outlets = JSON.parse(appSettings.getString("outlets"))` and `outlets[comboOutlets.get("selectedIndex")].nameOutlets`

Its work. Questions : any problems with this methods ?
Thanks

**Comment by PeterStaev** [comment]
@Jayuda the only thing I'm not sure is that `comboOutlets.get("selectedIndex")` will work as expected. The `selectedIndex` is a property of the DropDown, so I think the correct way to get the index would be: `comboOutlets.selectedIndex` (assuming `comboOutlets` is instance of the DropDown widget)
