### ISSUE TITLE
Add events for when the popup is opened, and when selection changes

### ISSUE THREAD

**Issue by PeterStaev** [PeterStaev/NativeScript-Drop-Down#20]
From @hvadotnarola [here](https://github.com/PeterStaev/NativeScript-Drop-Down/issues/19#issuecomment-231026701):

> Hey is there method to be called upon opening popup and on selection(Closing) ?

**Comment by hchor** [comment]
:+1: should have an optional event handler to do something if something is selected.

**Comment by hvadotnarola** [comment]
For now i have found a way around this with observer change listener where i can listen for selected index change value. 
`observableObject.on(observableModule.Observable.propertyChangeEvent, function(propertyChangeData){
 console.log(propertyChangeData.propertyName + " has been changed and the new value is: " + propertyChangeData.value);
});`

**Comment by relvis** [comment]
Any update in this section??? 

Thanks!

**Comment by PeterStaev** [comment]
Hey @relvis , this is on my radar, but sadly not much time lately to add couple of long awaited functions (including this one). Stay tuned :)
