### ISSUE TITLE
Is there a way to display iOS dropdown same like android like open drop-down at that place only not like bottom of the screen?

### ISSUE THREAD

**Issue by ruchitaecor** [PeterStaev/NativeScript-Drop-Down#200]
Hi, Greetings!!
I know its iOS native functionality to open a dropdown at bottom of the screen but I don't want like that in iOS. I want the same styling in iOS like Android. So is this possible with this plugin?

**Comment by PeterStaev** [comment]
Hi @ruchitaecor , this is not possible and I do not have plans of adding such a functionality. This plugin will follow design guidelines for each platform.
