### ISSUE TITLE
On Android works fine but on iOS gives an error on the ValueList

### ISSUE THREAD

**Issue by gsarme** [PeterStaev/NativeScript-Drop-Down#203]
On Android works pretty well but on iOS gives this error 

>  ERROR TypeError: undefined is not an object (evaluating 'this._listPicker.reloadAllComponents')

Moreover, always on iOS, it doesn't load all the items of the ValueList. I take the values from a REST request.

This is my _home.component.html_
```
<DropDown id="impianto"
                       [items]="impianti"
                       (selectedIndexChanged)="onChangeImpianto($event)"
                       [selectedIndex]="selectedIndex"
                       col="1"
                       ios:backgroundcolor="white"></DropDown>
```

And this is my _home.component.ts_

```
export class HomeComponent implements OnInit {
public impianti;
  constructor(){
    this.impianti = new ValueList<string>();
  }

  ngOnInit(){
    //...some code...
    this.ritiriService.getImpianti().subscribe((res) => {
        for(var i=0; i<res.length;i++){
           var str = JSON.stringify(res[i]);
           var obj = JSON.parse(str);
           this.impianti.push({ value: res[i].IdImpianto + ";" +res[i].IdSoggetto, display: res[i].IndirizzoCompleto});
        }
      },
      (err)=>{
        console.log("Something went wrong " + err);
        }
      );
     //...some code...
    }
}
```

**Comment by PeterStaev** [comment]
Hey @gsarme , It is not a good idea to directly push to the property that you have bound to the widget as with each push it causes change detection and a refresh on the widget. Not sure if this might be causing the problem for iOS. 

Please refer to the `demo-ng` project in this repo which have the drop down working fine in both iOS and Android. If you are still having problems please provide a reproducible example using the NativeScript Playground

**Comment by gsarme** [comment]
I follow the `demo-ng` project, I solved only a part of the problem. I moved a piece of the code to ngOnInit(), but I have to load another ValueList for a second DropDown when the value of the first one is changed and therefore the problem remains. How can I solve?

**Comment by PeterStaev** [comment]
I do not understand, in the above code there is no second drop down. For the second drop down are you again pushing the values NOT directly in the bound property but on local variable and then assigning the variable to the public bound property?

Again best is if you can provide a dummy reproducible example in the Playground.

**Comment by gsarme** [comment]
I'm trying to reproduce the error with Playground. 
Before I will try to solve the problem in the way you suggest.

**Comment by gsarme** [comment]
In Playground I can't import `nativescript-drop-down`. How can I reproduce the error?

**Comment by PeterStaev** [comment]
You need to go to the top left `+` and add an NPM package, then search for the plugin. Note that it is added in your project root, not in the `node_modules` folder like in a local project. So all your imports should be changed to accommodate this. 

Here is a template project for your convenience: https://play.nativescript.org/?template=play-ng&id=eE6Oqy&v=2

**Comment by gsarme** [comment]
Here is my [Playground](https://play.nativescript.org/?template=play-ng&id=gEVC9a&v=1). 
The logic is the same but I take the data from the server. Maybe the error is due to the presence of the tabview.  More than one tab has the dropdown, but in all of them the code is similar.

**Comment by PeterStaev** [comment]
> Here is my [Playground](https://play.nativescript.org/?template=play-ng&id=gEVC9a&v=1) (in this case it doesn't give the error).

If the error is not reproduced then not much I can do.

**Comment by gsarme** [comment]
I solved. I wasn't declare the variable in the correct place.
