### ISSUE TITLE
Set drop-down displayed value on resume

### ISSUE THREAD

**Issue by mrwrighty** [PeterStaev/NativeScript-Drop-Down#206]
I have the option to remember the last choice when my app resumes, however I cannot get the drop-down to display the last selected value.

I create an appSettings value when the drop-down is initially selected and need to use this value to set the drop-down on resume.

Thanks in advance

**Comment by PeterStaev** [comment]
@mrwrighty , this is a very specific use case and I cannot say what might be wrong. I suspect there is a problem with your saved value or the items in the drop down are not loaded when you try to set the value. If you can create a reproducible example on the NS Playground might be able to see in more details what could be wrong.

**Comment by PeterStaev** [comment]
No further response so closing this one for now. In case you still have problems, please provide more details.
