### ISSUE TITLE
nativescript-drop-down:Cannot read property 'open' of undefined

### ISSUE THREAD

**Issue by dev0304** [PeterStaev/NativeScript-Drop-Down#214]
I cannot open dropdown on button click 
I used below code in my Nativescript Angular Project

let dropdown = <DropDown>this.page.getViewById('ddstates');
dropdown.open();

It shows Cannot read property 'open' of undefined in terminal

**Comment by PeterStaev** [comment]
Hey @dev0304 , make sure you are calling it in the right place (i.e. the widget has been initialized). Consult with the demos in the repo.

**Comment by PeterStaev** [comment]
No further response so closing this one for now. In case you still have problems, please provide more details.
