### ISSUE TITLE
Is there a way to align the selected item to the right?

### ISSUE THREAD

**Issue by Jamiek94** [PeterStaev/NativeScript-Drop-Down#219]
Is it possible to only align the selected item to the right on android? It seems to be aligned to the left. I've tried several CSS styles like text-align & horizontal-align, but without success.

![image](https://user-images.githubusercontent.com/4362445/63228524-69a34700-c1f4-11e9-8641-d01878a4e650.png)

**Comment by AWhiteSheep** [comment]
You could try textAlignment attribute `DropDown textAlignment="right"` .

**Comment by Jamiek94** [comment]
The textAlignment didn't work for me. I had to set the gravity;

```
 const dropdown = this.page.getViewById<DropDown>("countryId");
 dropdown.nativeView.setGravity(8388613); // means gravity END.
```
