### ISSUE TITLE
onSelect event in not working in dropdown

### ISSUE THREAD

**Issue by suralal** [PeterStaev/NativeScript-Drop-Down#22]
hi,

I have tried (selectedIndexChange) event which is specified in the agular documentation.which is not working nativescript js code.how the get event call for onselect.

**Comment by SjurWarEagle** [comment]
I'm using

```
        <DropDown #ddLocation
                  id="ddLocation"
                  [items]="locations"
                  (selectedIndexChange)="onLocationChanged(ddLocation.selectedIndex)"
                  class="filterbar-selection"
        ></DropDown>

```

```
    onLocationChanged(index:number) {
        console.log("FilmFilterBar selected " + index);
    }

```

it works fine. What's your code?

**Comment by PeterStaev** [comment]
Hey @suralal , currently the `selectedIndexChanged` event works only for Angular + {N}. For regular {N} the event will be added with #20 .
