### ISSUE TITLE
Performance Issue with FlexboxLayout

### ISSUE THREAD

**Issue by dothem1337** [PeterStaev/NativeScript-Drop-Down#223]
Hi there

I encountered a performance problem, when using the DropDown into FlexboxLayout. Anyone else encountering this?

I'm using Nativescript with Angular. If I put the DropDown outside of the FlexboxLayout, the DropDown opens immediately. If not, it's very slow and slows down the whole page (also TextFields are slow).

**Comment by PeterStaev** [comment]
Hi @dothem1337 , you say that TextFields are also slow, which is a built in control, so it might be something related to the way you use the flexbox or some problem with the framework itself. Have you submitted an issue on the NativeScript repo?

**Comment by dothem1337** [comment]
The TextFields are only slow, if there is a DropDown available. Otherwise they are fast. So its depending on DropDown. Because it slows everything down, when its there.

**Comment by PeterStaev** [comment]
On what OS is this? I've just created a playground and at least on iOS I don't notice any slows:
https://play.nativescript.org/?template=play-ng&id=L3lXZ5&v=2

**Comment by PeterStaev** [comment]
No further response so closing this one for now. In case you still have problems, please provide more details.
