### ISSUE TITLE
Error with NativeScript 6.2

### ISSUE THREAD

**Issue by ashraf-jabr** [PeterStaev/NativeScript-Drop-Down#229]
After upgrading to NS 6.2 I am getting this error when building project:

**error TS2307: Cannot find module 'nativescript-angular/forms/value-accessors/base-value-accessor'.**

**Comment by PeterStaev** [comment]
@ashraf-jabr , make sure your project uses the "old" package of "nativescript-angular" and not the new one "@nativescript/angular". I will be adjusting the ProPlugins version to use the new scope packages soon 😄

**Comment by Sahkay** [comment]
I am using nativescript-angular (without the @) myself and am getting the same error now. I am currently looking for a manual fix but thought I'd post here in case I am more likely to get a response if I comment earlier due to timezones.

**Comment by PeterStaev** [comment]
Seems there might have been some code reorganization in the angular package. I have to check what might be the problem.

**Comment by DickSmith** [comment]
@ashraf-jabr @Sahkay 
In your webpack.config.js change the alias to this:
```
     alias: {
        "~": appFullPath,
        "nativescript-angular": "@nativescript/angular",
      },
```

**Comment by ashraf-jabr** [comment]
@DickSmith , I tried changing the alias but it still not working, maybe I miss something. However, my project uses 'nativescript-angular' not '@nativescript/angular' but it gives the same error at build time.

**Comment by PeterStaev** [comment]
Just a bit of a follow up - I just updated the ProPlugins `demo-ng` project using `tns update` and all seems to be working fine. So you should try to nuke your platforms/node_modules and try updating the app using the built in command.

**Comment by ashraf-jabr** [comment]
I think that 'base-value-accessor' is missed from the new version of 'nativescript-angular' package

**Comment by PeterStaev** [comment]
@ashraf-jabr , like I said above, I'm having no problems after upgrading the demo apps in ProPlugins, and they import the accessor from the same place.

**Comment by ashraf-jabr** [comment]
It now build with no errors after updating to 
"nativescript-angular": "8.20.1"
