### ISSUE TITLE
Ability to style the dropdown with CSS.

### ISSUE THREAD

**Issue by spstratis** [PeterStaev/NativeScript-Drop-Down#23]
This may be more of an enhancement than an issue, but is it possible to style the list popup with CSS? If not, is their another method in which I can slight update the styling of the popup?

**Comment by PeterStaev** [comment]
Hey @spstratis , currently the popup is styled together with the input field, where the selected value is shown. For example if you apply the following css:
```css
.test { 
background-color: red;
color: yellow;
}
```
The popup will be red and the text color will be yellow. Currently it is not possible to style the popup separate from the field.

**Comment by spstratis** [comment]
@PeterStaev Thank you for the info, one other question. Is the popup scrollable?

**Comment by SjurWarEagle** [comment]
Scrolling works fine for me.

**Comment by PeterStaev** [comment]
@spstratis Yes, the popup is scrollable (if you have enough items in it ;))

**Comment by himanshu331** [comment]
hi PeterStaev ,
I am using 
.test { 
background-color: red;
color: yellow;
}
this CSS 
i want to change only color of dropdown box not for GUI(like textfield)..
when i use background-color property then color of both side is changed..

**Comment by PeterStaev** [comment]
@himanshu331 , your behavior is not supported out of the box, and I do not think I will add suport for it as it is not consistent (like in HTML if you apply a background it is applied to both element and popup). So you will have to manually tinker and implement such behavior.

**Comment by alexisconsuegra** [comment]
I think it is an important feature to style the drop-down popup separated from the text field. It is very common to display the test left aligned but the list in the popup to be centered.

**Comment by sbacon94** [comment]
Hi There. Is it now possible to style the drop-down popup separate from the text field?

**Comment by sbacon94** [comment]
I want to use the popup in a form where the text is left aligned but have the popup text centered. See here - https://ibb.co/GWLVCsN
