### ISSUE TITLE
How can I reset the dd with the HINT value after selection of an item?

### ISSUE THREAD

**Issue by ittrad-mobile-lab** [PeterStaev/NativeScript-Drop-Down#231]
Doing selectedIndex = null and using the HINT attribute I've succeeded to initialize the dd with the HINT value which is awesome 👍 , 
but after selection of a certain item of dd the HINT value become unselectable so I wasn't able to reset the dd list.

Some trick? Any hint will be appreciated. 
Best

**Comment by PeterStaev** [comment]
If you want the user to be able to clear the value you can either add a button that will set the `selectedIndex` to `null` or you should add a default value item in the source of the drop down that will server as your not selected value.

**Comment by ittrad-mobile-lab** [comment]
The button solution was the most elegant for me. Many thanks for your quick support.

Hopefully you'll succeed to include this reset button on the new versions of that nice and very useful component.

**Comment by PeterStaev** [comment]
Well some people dont need such a think, or would like the default unselected value in the list itself. So I will leave the decision to the end user 😉
