### ISSUE TITLE
Property 'length' does not exist on type 'ValueList<string>'

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [PeterStaev/NativeScript-Drop-Down#233]
I am developing android and ios application using nativescript-angular. I have used the Drop-Down plugin for showing a list of security questions. When I was iterating the value list type array I have an error like "Property 'length' does not exist on type 'ValueList<string>'".How to fix the issue?

**Comment by PeterStaev** [comment]
Hey @ArigarasuthanRepo , I'm not sure how you are iterating but you need to use simple for loop and not `for...of...`. The `ValueList` extends the built in NS `ObservableArray` so you iterate both the same way.

**Comment by ArigarasuthanRepo** [comment]
I am iterating the array like:

```
var securityQuestion:ValueList<string>=new ValueList<string>();

securityQuestion = this.renderData();

 for(var k=0; k<this.securityQuestion.length; k++)
{
}

```

**Comment by PeterStaev** [comment]
This should work, but no idea what `renderData` does in your code. If you are still having problems create a reproducible example in the NS playground so I can take a look at it.

**Comment by ArigarasuthanRepo** [comment]
Render data is a function to render values to securityQuestion array.

```
    renderData()
    {
        var renderSpinnerArray:ValueList<string>=new ValueList<string>();
        let valueItems=[]
        for(var k=0; k<this.commonArray.length; k++)
        {
            valueItems.push({
                value:this.commonArray[k].id,
                display:this.commonArray[k].question
            });
        }

        renderSpinnerArray = new ValueList<string>(valueItems);

         return renderSpinnerArray;
    }
```

**Comment by ArigarasuthanRepo** [comment]
how to add your plugin to nativescript playground?

**Comment by ArigarasuthanRepo** [comment]
Hai, I was created project regarding dropdown in native script playground and added the drop-down plugin to the playground project but it returns an error like="Cannot find module 'nativescript-drop-down/angular'".

Screenshot:

![Screen Shot 2020-02-05 at 1 48 48 PM](https://user-images.githubusercontent.com/13533279/73823687-d18b2f80-481e-11ea-8235-09b0200c52ac.png)

**Comment by PeterStaev** [comment]
In the playground the NPM packages are added as folders to your project. So you need to import them with a relative path: `./nativescript-drop-down/angular` for example

**Comment by ArigarasuthanRepo** [comment]
it was also returns an same error.

**Comment by ArigarasuthanRepo** [comment]
Hello, are you there?. I did not get any response from you

**Comment by PeterStaev** [comment]
No idea why you are having problems. Here, it worked pretty straightforward. Here is the link:
https://play.nativescript.org/?template=play-ng&id=EVOojq

**Comment by ArigarasuthanRepo** [comment]
place your drop-down module in home.module.ts file.it is returns an error.

**Comment by PeterStaev** [comment]
Its called RELATIVE path not w/o a reason 😉 You need to adjust it
`import { DropDownModule } from "../nativescript-drop-down/angular"`

**Comment by ArigarasuthanRepo** [comment]
Ok thank you its worked.but returns an error while importing value list:
`import { ValueList } from "../nativescript-drop-down/angular"
`

**Comment by PeterStaev** [comment]
Sorry for the late response, just noticed that I did not answer your last question. You are importing the value list wrong, it should be:
`import { ValueList } from "../nativescript-drop-down"`

**Comment by PeterStaev** [comment]
No further response so closing this one for now. In case you still have problems, please provide more details.
