### ISSUE TITLE
Incompatibility: ios.utils.getter()  

### ISSUE THREAD

**Issue by JNicolasW** [PeterStaev/NativeScript-Drop-Down#234]
### tns-ios:  "6.2.0"
 ### tns-android: "6.3.0"

Hello, im developing and android/ios app, which it attempt to use drop-down as well in the web version.

In Android works fine with Nativescript 6, but its not such case with iOs. Im attempting to use the dropdown inside a bottomsheet, where it throws the error;  "ios.utils.getter() is a deprecated function, use the the native property instead.

I look around and it looks that the dropdown ios.js use it twice that function (ios.utils.getter) once to get the view context of the screen and then to set a background color. 

Does anyone have a solution to this issue? Thanks in advance.

**Comment by PeterStaev** [comment]
Hey @JNicolasW , you can fork the code and replace the function with the compatible version and then submit a PR so anyone in the community can benefit from your fix. 

This has already been fixed in the ProPlugins version, so if you are a subscriber, make sure you use the one available from there.
