### ISSUE TITLE
DropDown Item Selected

### ISSUE THREAD

**Issue by priyansh360** [PeterStaev/NativeScript-Drop-Down#238]
HI ,
Can you please tell me , if i can able to change the selected text from the drop to show when DropDown is closed.
Example:
If dropdown has first & lastname, on Selected i want to display only first name as selected item

**Comment by PeterStaev** [comment]
Hey @priyansh360 , the drop down doesnt support such behavior. Just like a normal HTML drop down whatever is in the drop  down popup, this is what the selected value would be.

**Comment by priyansh360** [comment]
okay , Thanks @PeterStaev
