### ISSUE TITLE
Assertion failure in -[UISectionRowData allocateArraysWithCapacity:forSection:]

### ISSUE THREAD

**Issue by nmandyam** [PeterStaev/NativeScript-Drop-Down#240]
My app was working OK for months (not recompiled), but as of last week's compile (where I made changes to a different set of pages), the page that has this drop-down fails with this error. The drop-down is used within a StackLayout two levels within a Repeater. The page itself loads OK, but when you click on the drop-down control in any of the Repeater sections, the app crashes with the named error.
Platform: iOS
NativeScript: 6.2, 6.3
Plugin version: nativescript-drop-down@5.0.4
Dependencies: Below

I have cleaned out node-modules, platforms and hooks, even reinstalled NativeScript (gone from 6.3 to 6.2 and back), still fails. I have also checked for the usual hazards of null values in the dd values and so on, no issues there either.

What could be causing this problem and how can I fix it? Thanks for a terrific control!

`
  "dependencies": {
    "@nstudio/nativescript-cardview": "^1.0.0",
    "@nstudio/nativescript-checkbox": "^1.0.0",
    "@nstudio/nativescript-floatingactionbutton": "^2.0.0",
    "cookie": "^0.3.1",
    "crypto-js": "^3.1.8",
    "delay": "^4.3.0",
    "email-validator": "^2.0.3",
    "moment": "^2.14.1",
    "moment-timezone": "^0.5.23",
    "nativescript-app-sync": "^2.0.0",
    "nativescript-background-http": "^4.2.1",
    "nativescript-barcodescanner": "^3.4.2",
    "nativescript-camera": "4.5.0",
    "nativescript-cfalert-dialog": "^1.0.15",
    "nativescript-dom": "^2.0.5",
    "nativescript-drawingpad": "^3.1.0",
    "nativescript-drop-down": "^5.0.4",
    "nativescript-exit": "^1.0.1",
    "nativescript-fancyalert": "^3.0.9",
    "nativescript-filter-select": "^1.3.0",
    "nativescript-geolocation": "^5.1.0",
    "nativescript-gradient": "^2.0.1",
    "nativescript-imagepicker": "^7.1.0",
    "nativescript-keyboardshowing": "^1.0.2",
    "nativescript-modal-datetimepicker": "^1.2.2",
    "nativescript-multi-select": "^1.0.6",
    "nativescript-numeric-keyboard": "^4.3.1",
    "nativescript-orientation": "^2.2.4",
    "nativescript-plugin-firebase": "^10.3.3",
    "nativescript-statusbar": "^5.0.0",
    "nativescript-timedatepicker": "^1.2.1",
    "nativescript-toast": "1.4.6",
    "nativescript-ui-chart": "^7.1.1",
    "nativescript-ui-listview": "^8.0.1",
    "nativescript-ui-sidedrawer": "^8.0.0",
    "node-schedule": "^1.3.2",
    "promise-map-series": "^0.2.3",
    "tns-core-modules": "^6.5.1"
  },
  "devDependencies": {
    "babel-traverse": "6.13.0",
    "babel-types": "6.13.0",
    "babylon": "6.9.0",
    "lazy": "1.0.11",
    "nativescript-dev-webpack": "^1.4.1"
  },
`

**Comment by PeterStaev** [comment]
Hey @nmandyam , are you sure it is the drop down that is causing the error? I can't find any reference to `UISectionRowData` in the drop down code.

**Comment by nmandyam** [comment]
All other controls on screen work OK; clicking on any of the drop-downs on screen crashes the app. So I assumed that's the problem. Now that you've raised the question, I'll see if I can isolate things better. Will report back here. Thank you for the quick response!

**Comment by nmandyam** [comment]
Figured this out - at least, what I THINK was the issue. I had referred to a class that did not exist. Once I defined that class, all is well. Strange, but true. Thanks!
