### ISSUE TITLE
Ivy support

### ISSUE THREAD

**Issue by relez** [PeterStaev/NativeScript-Drop-Down#245]
Hi there... I am getting this error when trying to run my app on iOS:

`tns run ios --env.aot`

`This likely means that the library (nativescript-drop-down/angular) which declares DropDownModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.`

Do I need to do any further configuration on `ngcc.config.js` file?

Thanks!

**Comment by PeterStaev** [comment]
Hey @relez , 

I've just tested and Ivy support is present in the [ProPlugins NPM](https://npm.proplugins.org) version of the plugin. 

All future work of this plugin will be available exclusively as part of ProPlugins initiative. So if you want to get the latest updates/fixes/features make sure you [subscribe to the service](https://proplugins.org/subscribe.html). You get all my plugins plus many of the most used and high quality plugins for a small monthly subscription fee.

**Comment by PeterStaev** [comment]
Actually further looking I was wrong, and from what I see there is no guide on how to migrate plugins...

**Comment by PeterStaev** [comment]
Angular 9 Support is now available in the new version of the plugin available in the [ProPlugins NPM](https://npm.proplugins.org) registry. 

All future work of this plugin will be available exclusively as part of ProPlugins initiative. So if you want to get the latest updates/fixes/features make sure you [subscribe to the service](https://proplugins.org/subscribe.html). You get all my plugins plus many of the most used and high quality plugins for a small monthly subscription fee.
