### ISSUE TITLE
FPS is not 60

### ISSUE THREAD

**Issue by ukik** [PeterStaev/NativeScript-Drop-Down#246]
I use this but when it drop drown is slow lagging

**Comment by PeterStaev** [comment]
Are you making a game with the drop down plugin or why do you need 60 FPS 😄 

Sadly I can't help you with this. The drop down uses the standard virtualization provided in each platform, so it loads only the data it needs. and not all items. So I dont think anything else can be done so it is more optimized.

**Comment by ukik** [comment]
> Are you making a game with the drop down plugin or why do you need 60 FPS 
> 
> Sadly I can't help you with this. The drop down uses the standard virtualization provided in each platform, so it loads only the data it needs. and not all items. So I dont think anything else can be done so it is more optimized.

What i mean is this plugin when popup show-in is slower than popup show-in which actionbar does.

**Comment by PeterStaev** [comment]
Sorry but i dont understand you :(
