### ISSUE TITLE
Support to @nativescript/angular

### ISSUE THREAD

**Issue by juniorschen** [PeterStaev/NativeScript-Drop-Down#247]
Add new version to support @nativescript/angular instead of  nativescript-angular

**Comment by PeterStaev** [comment]
This is available in the  [ProPlugins NPM](https://npm.proplugins.org) version of the plugin. 

All future work of this plugin will be available exclusively as part of ProPlugins initiative. So if you want to get the latest updates/fixes/features make sure you [subscribe to the service](https://proplugins.org/subscribe.html). You get all my plugins plus many of the most used and high quality plugins for a small monthly subscription fee.

**Comment by juniorschen** [comment]
@PeterStaev 
Thanks for the support all this time, good luck with the Pro plugins
