### ISSUE TITLE
Error after upgrading Nativescript

### ISSUE THREAD

**Issue by mrwrighty** [PeterStaev/NativeScript-Drop-Down#252]
I'm getting this error when using ns run ios or ns run android

Android version runs irrespective of the error but error does display. iOS version fails to compile and run

ERROR in ../node_modules/nativescript-drop-down/drop-down.js
Module not found: Error: Can't resolve 'ui/editable-text-base/editable-text-base' in '/Users/nick/Documents/NativeScript/Projects/WFSL/node_modules/nativescript-drop-down'
 @ ../node_modules/nativescript-drop-down/drop-down.js 6:27-78
 @ ./views/settings/settings-page.xml
 @ . sync (?<!\bApp_Resources\b.*)(?<!\.\/\btests\b\/.*?)\.(xml|css|js|(?<!\.d\.)ts|(?<!\b_[\w-]*\.)scss)$
 @ ./app.js

Version of Dropdown is 5.0.6

I have removed and re-added the plugin

ns doctor returns

✔ Your ANDROID_HOME environment variable is set and points to correct directory.
✔ Your adb from the Android SDK is correctly installed.
✔ The Android SDK is installed.
✔ A compatible Android SDK for compilation is found.
✔ Javac is installed and is configured properly.
✔ The Java Development Kit (JDK) is installed and is configured properly.
✔ Xcode is installed and is configured properly.
✔ xcodeproj is installed and is configured properly.
✔ CocoaPods are installed.
✔ CocoaPods update is not required.
✔ CocoaPods are configured properly.
✔ Your current CocoaPods version is newer than 1.0.0.
✔ Python installed and configured correctly.
✔ The Python 'six' package is found.
✔ Xcode version 11.7.0 satisfies minimum required version 10.
✔ Getting NativeScript components versions information...
✔ Component nativescript has 7.0.8 version and is up to date.
✔ Component @nativescript/core has 7.0.3 version and is up to date.
✔ Component @nativescript/ios has 7.0.0 version and is up to date.
✔ Component tns-android has 6.5.3 version and is up to date.

**Comment by mrwrighty** [comment]
Just seen the reference to this version not being compatible with Nativescript 7. Do you have any timescale for a compatible version.

**Comment by PeterStaev** [comment]
Hey @mrwrighty , the compatible version is already on the [ProPlugins NPM](https://npm.proplugins.org). You need to have an active [subscription](https://proplugins.org/subscribe.html) in order to gain access to it.

**Comment by mrwrighty** [comment]
We only do ad-hoc simple apps and cannot justify the subscription for these plugins. its a real shame. I realise you have to make money from this, but our projects cannot justify this as an on-going cost. Nativescript seem to forget that not all companies are big developers with big plugin needs that can justify the monthly cost.

**Comment by PeterStaev** [comment]
@mrwrighty , I can understand that. First of all let me be clear that ProPlugins is unrelated to NativeScript or nStudio. This is an independent initiative I joined, because I could not justify all the time spent to support all my plugins with all the breaking changes coming with almost every version of NS. 

You can check the code in this repo and try to make it compatible with NS 7. I would gladly approve a PR from which the whole community can benefit. 
You can also subscribe for a month and download the package and use it in your apps even after the subscription expires.

**Comment by mrwrighty** [comment]
Thank you for the clarification. I will have to discuss this with our bosses but I'm not expecting good news.
