### ISSUE TITLE
When is coming a new version for N 7 ?

### ISSUE THREAD

**Issue by Slymn10** [PeterStaev/NativeScript-Drop-Down#255]

**Comment by PeterStaev** [comment]
Hey @Slymn10 , as per the readme all new versions are released as part of the [ProPlugins](https://proplugins.org/subscribe.html) subscription. And there is a NS7 compatible version there almost right after NS7 was released. 

If you cannot subscribe, then the only other option is to clone the code and make it compatible with NS7 yourself. I'm happily accepting PRs to this repo :) Or you can redesign your UI to not require the use of a drop down.
