### ISSUE TITLE
TypeError while trying to use it in nativescript-angular

### ISSUE THREAD

**Issue by noerK** [PeterStaev/NativeScript-Drop-Down#26]
Hey Guys,

im running an angular-nativescript project and tried to use this module. I just added the example code, but it just shows:

`TypeError: Could not load view for: DropDown.TypeError: Attempted to assign to readonly property.`

I tried to change the register element to another element-name as DropDown and i tried to remove the "use strict"; in the module code, but nothing helped.

my versions:

tns-ios: 2.1.1,
tns-core-modules: 2.1.0,
nativescript-angular: "next"

I hope you can help me out :)

**Comment by PeterStaev** [comment]
Hey @noerK , I just tried couple of scenarios and from I cannot simulate this. Can you please provide detailed code sample or sample project?

**Comment by rmorameneses** [comment]
I got it!!, just update

**Comment by PeterStaev** [comment]
No response, closing this one.
