### ISSUE TITLE
Provide a way to style the currently selected item

### ISSUE THREAD

**Issue by adrienbusin** [PeterStaev/NativeScript-Drop-Down#28]
Hi,
Is it possible to show witch item is selected ?
Change its color for instance ? 
like -> item1 
            item2 (colored)
            item3

Thanks

**Comment by hvadotnarola** [comment]
+1

**Comment by cagatayoncul** [comment]
+

**Comment by PeterStaev** [comment]
This is now available in the new version of the plugin available in the [ProPlugins NPM](https://npm.proplugins.org) registry. 

All future work of this plugin will be available exclusively as part of ProPlugins initiative. So if you want to get the latest updates/fixes/features make sure you [subscribe to the service](https://proplugins.org/subscribe.html). You get all my plugins plus many of the most used and high quality plugins for a small monthly subscription fee.
