### ISSUE TITLE
How to SetPrompt ?

### ISSUE THREAD

**Issue by adrienbusin** [PeterStaev/NativeScript-Drop-Down#29]
Is it possible to setPrompt ? (this._android.setPrompt("Select your favorite ... ") )

Thanks a lot

**Comment by PeterStaev** [comment]
Hey @adrienbusin , setting the `hint` property does something similar, but not the exactly same. 

Since `setPrompt` is android specific and there is no analogue in iOS I will not add this as a property to the widget. But nonetheless you can set it with the code you provided above.
