### ISSUE TITLE
Drop down type error 

### ISSUE THREAD

**Issue by akkiittiwari** [PeterStaev/NativeScript-Drop-Down#3]
item._getItemId is not a function on dropdown use in my xml file.

here is the xml and js file code respectively:

                <dd:DropDown icon="res://ic_overflow" items="{{ items }}" selectedIndex="{{ selectedIndex }}" position="right" />

***********************************************************************

    var items = new observableArray.ObservableArray();

    for (var loop = 0; loop < 20; loop++)
    {
        items.push("Item " + loop.toString());
    }
    pageData.set("items", items);
    pageData.set("selectedIndex", 15);
    pageData.set("ScrollView", scrollView);
    
    page.bindingContext = pageData;

**Comment by PeterStaev** [comment]
What version of {N} are you using? I've just tried with 1.4.3 and your code is working fine

**Comment by akkiittiwari** [comment]
sorry, a little late for the reply. Let me try and let you know.

**Comment by PeterStaev** [comment]
I've upgraded the code to use {N} 1.5.2 and i still do not experience the problem you described.

**Comment by bpanatta** [comment]
You've said your problem was with: 
> item._getItemId

Shouldn't it be: item**s**._getItemId ?
