### ISSUE TITLE
Hint disappearing as soon as items bound

### ISSUE THREAD

**Issue by toddanglin** [PeterStaev/NativeScript-Drop-Down#31]
Is there a trick to getting the "hint" to stay visible _until_ an user has interacted with the DropDown? In my tests, the hint is immediately hidden as soon as I set the `items` property.

I've tried both declarative and imperative binding:

```
<dd:DropDown items={{ myItems }} hint="Choose one..." id="ddTest" />
OR
let dd = page.getViewById("ddTest");
dd.items = myItems;
```

I see the hint on the screen briefly, but it is quickly replaced with the first item from the bound list (before any user interaction). Any ideas?

FWIW, I'm on iOS and I'm using the `ValueList`/`IValueItem` approach described in the docs.

**Comment by PeterStaev** [comment]
Hey @toddanglin , seems this is a bug when you do not have the `selectedIndex` property bound. As a temporary workaround you can bind the `selectedIndex` to an `undefined` or `null` property.
