### ISSUE TITLE
NS+angular 2 Webpack problem

### ISSUE THREAD

**Issue by adisoftbn** [PeterStaev/NativeScript-Drop-Down#35]
Hello,

I saw that there is an incompatibility between dropdown plugin and WebPack plugin.

The error you get is "Trying to link invalid 'this' to a Java object".

If i remove the plugin everything seems to work.

**Comment by PeterStaev** [comment]
Hey @adisoftbn , the error does not hint at a problem with the plugin, but more with the way you have it set up/use it. Can you provide more details where does this error happen?

**Comment by adisoftbn** [comment]
Hello,

Sorry for delay.

Everything works fine if i dont use --bundle.

If i install webpack and use the --bundle option at build, It breaks at "_super.apply(this, arguments);" from line 37(drop-down.android.ts) with the error "Trying to link invalid 'this' to a Java object". If I remove the plugin(and another plugin which seems to have the same problem) from the project it seems to work

I have an angular project. I tried to reproduce the issue on "https://github.com/PeterStaev/ng-test-bed.git" but I need to update it to the latest version of angular2 because there seem to be some issues when running it like it is now... I will try to get free time to update it tomorrow.

**Comment by PeterStaev** [comment]
Hey @adisoftbn , I've just published a new version on NPM (1.3.3) with a possible fix for this. Can you try to upgrade the plugin in your project and see if the problem still persists?

**Comment by adisoftbn** [comment]
Sorry for the delay :D I had a lot of other problems to solve.

I can confirm that there isn't any other issue with webpack.
Everything work flawless :D

Best regards !
