### ISSUE TITLE
Cann't Find name'UITextField' and 'android'

### ISSUE THREAD

**Issue by chanmyaethu-mn** [PeterStaev/NativeScript-Drop-Down#40]
Hi Peter,
I have problem which is followed as below,

node_modules/nativescript-drop-down/drop-down.d.ts(31,14): error TS2304: Cannot find name 'UITextField'.

node_modules/nativescript-drop-down/drop-down.d.ts(32,18): error TS2503: Cannot find namespace 'android'.

May I know your suggestion?

Thanks
Chan Myae Thu

**Comment by PeterStaev** [comment]
Hey @chanmyaethu-mn , take a look at the 2nd part of this comment: https://github.com/PeterStaev/NativeScript-Drop-Down/issues/39#issuecomment-252548468

**Comment by stvnmntjy** [comment]
Not to resurrect this issue, but some thoughts:

1. Update the `README` with **complete** documentation on how to use this plugin, esp. in an NativeScript-Angular 2 project.
1. Add a NativeScript-Angular 2 working demo in the `/sample` directory that adds no more to, takes no less than, what is documented in the `README`. I notice that the NativeScript-core example you have adds these typings you've referenced (in the above link), yet they are not mentioned anywhere in the `README`.
1. Is there a way/is it feasible to push those implementation-specific declarations (in `drop-down.d.ts`) down into their respective implementation files? (`drop-down.android.ts`, `drop-down.ios.ts`) Would this remove the need to add these additional typings? (new to {N}, just askin')

(just as a side-note: adding these typings only brings about more errors for me with in a `nativescript@2.4.2` project)

Great work, Peter, in this strangely sparse area of "dropdowns/selects" in NativeScript.

**Comment by PeterStaev** [comment]
@stvnmntjy , the readme is complete for the Angular 2 type of project. For the `d.ts` with new versions of TypeScript (2.1+) seems those are automatically resolved within the packages. I just tried with 2.1.5 and removed the reference in the `reference.d.ts` file and the project still works. 

As for the compile errors I've already explained in the comment above - those can be ignored or you can add and reference `tns-platform-declarations` module to fix those.

**Comment by stvnmntjy** [comment]
I guess that's the points I'm bringing up. Rather than have your plugin consumers dig through closed issues for what will inevitably happen, having these addressed upfront in the `README` would go a long way toward seamless adoption.

And re: 

> I just tried with 2.1.5 and removed the reference in the reference.d.ts file and the project still works.

... again, having an Angular 2 sample project in the `sample` directory would be a great baseline for discussions in any future Angular issues.
