### ISSUE TITLE
Change color of just the drop down

### ISSUE THREAD

**Issue by 9thwall** [PeterStaev/NativeScript-Drop-Down#44]
Hi! 
I was wondering if it was possible to change the background color of just the drop down pop up.

**Comment by PeterStaev** [comment]
Hey @9thwall , currently this is not possible, and I'm not sure it is such a good idea to implement. I will leave this for now open to see if there is a real need for this.

**Comment by 9thwall** [comment]
@PeterStaev Ok no problem. The only reason I'm looking for this feature is because I have a dark image background and the drop down font color is by default a dark color. If I make the drop down background color dark then it also makes the field have a background color which would cover part of the background image. Anyway, thank you for the update.

**Comment by hvadotnarola** [comment]
@PeterStaev can we style hint ?

**Comment by PeterStaev** [comment]
This is now available in the new version of the plugin available in the [ProPlugins NPM](https://npm.proplugins.org) registry. 

All future work of this plugin will be available exclusively as part of ProPlugins initiative. So if you want to get the latest updates/fixes/features make sure you [subscribe to the service](https://proplugins.org/subscribe.html). You get all my plugins plus many of the most used and high quality plugins for a small monthly subscription fee.
