### ISSUE TITLE
Reset dropdown value back to 0 index

### ISSUE THREAD

**Issue by aldomatic** [PeterStaev/NativeScript-Drop-Down#46]
Is there a way one can reset the index on the dropdown back to 0 index?

Thanks

**Comment by PeterStaev** [comment]
Hey @aldomatic , just get a reference to the DropDown widget in your page and then use the `selectedIndex` property and set it to 0. 
```ts
let dd = page.getViewById<DropDown>("dd");
dd.selectedIndex = 0
```
Or if you have your drop down bound to some model, simply set the field to which you bound the `selectedIndex` property to 0)

**Comment by Rjitendra** [comment]
how to implement it in nativescript angular2
