### ISSUE TITLE
Blank Titles

### ISSUE THREAD

**Issue by Milewski** [PeterStaev/NativeScript-Drop-Down#5]
if i build up the ObservableArray with local data it`s fine, however if i am to pass an empty ObservableArray and populate it later i end up with all blank values on the dropdown.

```
var modelArray = new ObservableArray();

anotherObservable.on(Observable.propertyChangeEvent, function (data) {
  for (var item in data){
     modelArray.setItem(data[item].id, data[item].name)
  }
});

this.set('dropdown', modelArray)

```

**Comment by PeterStaev** [comment]
Hey @Milewski . changing data in ObservableArray does not cause widgets to be redrawn. For example you can try the same example you gave but with a ListPicker {N} widget. So this does not relate to the drop down widget. In order for it to work you must change your code as follows:
```JS
var modelArray = new ObservableArray();

anotherObservable.on(Observable.propertyChangeEvent, function (data) {
  var items = new ObservableArray();
  for (var item in data){
     items .setItem(data[item].id, data[item].name)
  }
  this.set('dropdown', items);
});

this.set('dropdown', modelArray)
```
