### ISSUE TITLE
Rest the drop down to its original state

### ISSUE THREAD

**Issue by gazlu** [PeterStaev/NativeScript-Drop-Down#54]
There is no way to reset the drop down where the hint is shown and items are refreshed and waiting to be refreshed.

**Comment by PeterStaev** [comment]
Hey @gazlu , can you provide more details/code sample on this. I have initialized a dropdown w/o any items and then after some timeout set the items to some array and the items are visible in the drop down.

**Comment by PeterStaev** [comment]
No response, closing this one. If you still have problems reopen it and provide more details.
