### ISSUE TITLE
Provide ability to style hint color

### ISSUE THREAD

**Issue by PeterStaev** [PeterStaev/NativeScript-Drop-Down#55]
From @hvadotnarola

**Comment by majorpaynegh** [comment]
how about styling the font size of the items and hint??

**Comment by PeterStaev** [comment]
@majorpaynegh , this is already possible. You can see it in the sample app.

**Comment by xyh67** [comment]
@PeterStaev So how can I change hint color?I don't find the way to change color.thx

**Comment by PeterStaev** [comment]
@xyh67 , the issue is still open, so this is not possible yet. The previous comment was about setting the font size of items.

**Comment by razorsyntax** [comment]
@PeterStaev Is this ability to modify the hint color almost ready for primt time?  I'm using a dark theme and the user can't see the hint at all on iOS.  Any up dates on this?

**Comment by PeterStaev** [comment]
@razorsyntax , no work has been done on this yet.

**Comment by tahir-jamil** [comment]
ya its a good effort wish to get that 
thanks for your awesome work @PeterStaev
