### ISSUE TITLE
Reset Dropdown to hint that has been

### ISSUE THREAD

**Issue by manishmlv50** [PeterStaev/NativeScript-Drop-Down#58]
Hey,

I am using this plugin with angular2 and typescript. 

                                <DropDown 
                                    #dd1
                                    class="dropdown input"
                                    hint="Select"
                                    [items]="categoryFlat" 
                                    [selectedIndex]="selectedIndex" 
                                    (selectedIndexChange)="onChange(dd1.selectedIndex)"  >

Is there a way where i can reset the dropdown to the hint & not to any index. 
Thank you.

**Comment by PeterStaev** [comment]
Hey @manishmlv50 , you should set the `selectedIndex` property of data model to `null`. Then the drop down will display the hint.

**Comment by manishmlv50** [comment]
Hey, Thanks for the update. 

I have two dropdown. One with category and other with list of interests in which the items of interests are dependent on the category. Everything is working fine, except when the category is changed the items in the interests dropdown is updated. But if an interests is already selected and the category is changed the previously selected interest still shows on the label, but the dropdown is updated.

On the category change event, I am setting the selectedIndex for interest to undefined. Still it is not updating the UI.

Can you please help with how can i update the label when the category changes.

**Comment by PeterStaev** [comment]
Hey @manishmlv50 , I've just tested with a setup similar to yours and everything seems to be working fine on both iOS and Android. Below is the sample code:
```ts
// main-page.ts
import { EventData, Observable} from "data/observable";
import { ObservableArray } from "data/observable-array";
import pages = require("ui/page");
import { SelectedIndexChangedEventData } from "nativescript-drop-down";

var viewModel: Observable;

export function pageLoaded(args: EventData) {
    var page = <pages.Page>args.object;
    var items = new ObservableArray();

    viewModel = new Observable();

    for (var loop = 0; loop < 200; loop++) {
        items.push("Cat " + loop.toString());
    }

    viewModel.set("categories", items);
    viewModel.set("items", null);
    viewModel.set("catHint", "Select Category");
    viewModel.set("hint", "Select an Item")
    viewModel.set("selectedCatIndex", null);
    viewModel.set("selectedIndex", null);

    page.bindingContext = viewModel;
}

export function dropDownOpened(args: EventData) {
    console.log("Drop Down opened");
}

export function dropDownSelectedIndexChanged(args: SelectedIndexChangedEventData) {
    viewModel.set("selectedIndex", null);
    let items = [];
    for (let loop = 0; loop < 10; loop++) {
        items.push(`Cat ${args.newIndex} - Item ${loop}`);
    }
    viewModel.set("items", items);
}
```

```xml
<!-- main-page.xml -->
<Page xmlns="http://schemas.nativescript.org/tns.xsd" loaded="pageLoaded" xmlns:dd="nativescript-drop-down">
  <GridLayout rows="auto, auto, *" columns="auto, *">
    <dd:DropDown id="dd" hint="{{ catHint }}" items="{{ categories }}" selectedIndex="{{ selectedCatIndex }}" 
                 opened="dropDownOpened" selectedIndexChanged="dropDownSelectedIndexChanged" 
                 row="0" colSpan="2" />

    <dd:DropDown hint="{{ hint }}" items="{{ items }}" selectedIndex="{{ selectedIndex }}" 
                 row="1" colSpan="2" />
  </GridLayout>
</Page>
```

**Comment by manishmlv50** [comment]
Thanks the Observables worked

**Comment by Rjitendra** [comment]
can u implement it on nativescript angular2

**Comment by PeterStaev** [comment]
Hey @Rjitendra , there is no difference for angular2, just set the `selectedIndex` to `null`.

**Comment by Rjitendra** [comment]
hi this is my code
.html
------
<DropDown #dd  class="dd" row="0" col="1" [items]="items" [selectedIndex]="selectedIndex" (selectedIndexChanged)="onchange1($event)" >
        </DropDown>
<Button class="sbtbtn" text="Add" (tap)="Add()"></Button>

.ts
------
let dd=page.getViewById<DropDown>("dd")
dd.selectedIndex = null;

**Comment by Rjitendra** [comment]
thanks bro got it.
