### ISSUE TITLE
Not working with Angular2

### ISSUE THREAD

**Issue by danrevah** [PeterStaev/NativeScript-Drop-Down#59]
For some reason I'm unable to figure out how to make this work with Angular2.
I've followed the instructions in the readme file which were pretty straight forward.
But after using the component in the view it's not showing any thing.

I'm using the sample-Groceries app https://github.com/NativeScript/sample-Groceries
as my nativescript playground.

Any idea?

**Comment by PeterStaev** [comment]
Hey @danrevah , the code in the readme works as I have a blank playground with the described files and it works. So I would suggest you start a blank app and start adding things. Then see what you have different in the groceries playground and see what you have missed.

**Comment by jaywebguy** [comment]
Help, I've tried search stackoverflow for any information concerning this. Anyhow, I'm getting the following error. I've followed the setup for angular 2 cutting and pasting the example. I'm guessing I'm missing some import in my solution somewhere?

node_modules/nativescript-drop-down/drop-down.d.ts(40,14): error TS2304: Cannot find name 'UILabel'.

node_modules/nativescript-drop-down/drop-down.d.ts(41,18): error TS2503: Cannot find namespace 'android'.

**Comment by PeterStaev** [comment]
@jaywebguy , take a look at https://github.com/PeterStaev/NativeScript-Drop-Down/issues/39#issuecomment-252548468 second part. Those are TS compile errors which can be ignored or you can add reference to the `tns-platform-declarations` module and references those to solve the problem.

**Comment by PeterStaev** [comment]
No response, so will close this for now. If you still have problems you can reopen and provide more details.

**Comment by x00** [comment]
"not working" is never a great title of an issue @danrevah always describe the specifics. 

@PeterStaev  the complier exits so can't be ignored. 

```
$ tns info
All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬───────────────┐
│ Component        │ Current version │ Latest version │ Information   │
│ nativescript     │ 2.5.0           │ 2.5.0          │ Up to date    │
│ tns-core-modules │ 2.5.0           │ 2.5.0          │ Up to date    │
│ tns-android      │ 2.5.0           │ 2.5.0          │ Up to date    │
│ tns-ios          │                 │ 2.5.0          │ Not installed │
└──────────────────┴─────────────────┴────────────────┴───────────────┘
```
```
$ adb shell getprop | grep "model\|version.sdk\|manufacturer\|hardware\|platform\|revision\|serialno\|product.name\|brand"
[ro.board.platform]: [msm8916]
[ro.boot.bootreason]: [hardware_reset]
[ro.boot.hardware]: [qcom]
[ro.boot.hardware.sku]: [XT1562]
[ro.boot.secure_hardware]: [1]
[ro.boot.serialno]: [ZY2226SJZ5]
[ro.bootreason]: [hardware_reset]
[ro.build.version.sdk]: [23]
[ro.hardware]: [qcom]
[ro.hw.revision]: [p2c]
[ro.kick.logcopy]: [hardware_reset]
[ro.mot.build.version.sdk_int]: [24]
[ro.product.brand]: [motorola]
[ro.product.manufacturer]: [motorola]
[ro.product.model]: [XT1562]
[ro.product.name]: [lux_reteu]
[ro.revision]: [p2c0]
[ro.serialno]: [ZY2226SJZ5]
```

**Comment by x00** [comment]
`UILabel` is an ios thing so I made these delectations 
```
/// <reference path="./node_modules/tns-platform-declarations/android.d.ts" />
/// <reference path="./node_modules/tns-platform-declarations/ios.d.ts" />
```

unfortunately this caused a future issue. 

```
node_modules/tns-platform-declarations/ios/objc-i386/objc!CoreAudio.d.ts(7,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'AudioBuffer' must be of type '{ new (): AudioBuffer; prototype: AudioBuffer; }', but here has type 'StructType<AudioBuffer>'.

node_modules/tns-platform-declarations/ios/objc-i386/objc!UIKit.d.ts(4954,15): error TS2300: Duplicate identifier 'UIEvent'.
node_modules/tns-platform-declarations/ios/objc-i386/objc!UIKit.d.ts(4954,15): error TS2417: Class static side 'typeof UIEvent' incorrectly extends base class static side 'typeof NSObject'.
  Types of property 'alloc' are incompatible.
    Type '() => UIEvent' is not assignable to type '() => NSObject'.
      Type 'UIEvent' is not assignable to type 'NSObject'.
        Property 'accessibilityActivationPoint' is missing in type 'UIEvent'.
node_modules/typescript/lib/lib.d.ts(14991,11): error TS2300: Duplicate identifier 'UIEvent'.
node_modules/typescript/lib/lib.d.ts(14997,13): error TS2300: Duplicate identifier 'UIEvent'.
```

not the fault of this project.

So I set `noEmitOnError:false` and removed the refences.

**Comment by b4rtt** [comment]
@x00 same error here

**Comment by PeterStaev** [comment]
@b4rtt , like @x00  mentioend above, you can simply disable `noEmitOnError`. In the core3 version I have removed the strong types to avoid those problems.
