### ISSUE TITLE
TypeError: Invalid Version: >=1.5.0

### ISSUE THREAD

**Issue by vchimev** [PeterStaev/NativeScript-Drop-Down#6]
In the *package.json* file of the plugin version 1.2.2 there is:
```
"nativescript": {
    "platforms": {
      "ios": ">=1.5.0",
      "android": ">=1.5.0"
    }
  }
```
which is not a valid version.

The same for https://github.com/PeterStaev/NativeScript-Grid-View/ plugin.

FYI: https://github.com/NativeScript/nativescript-cli/issues/1530

**Comment by PeterStaev** [comment]
Hey @vchimev , according to the [docs](https://docs.nativescript.org/plugins/plugins#packagejson-specification):

> It must contain a nativescript section which describes the supported NativeScript runtimes and their versions. This section can be empty. If you want to define supported platforms and runtimes, you can nest a platforms section. In this platforms section, you can nest ios and android key-value pairs. The values in these pairs must be valid runtime versions or **ranges of values specified by a valid semver(7) syntax**.

So as I was reading it the version should be considered valid, but i changed it before the discussion in the other task :) So seems the wording in the docs is wrong (for the current CLI version). I will see to fix the versions.
