### ISSUE TITLE
Close DropDown from .js code and add an onClose event

### ISSUE THREAD

**Issue by andreacappadona17** [PeterStaev/NativeScript-Drop-Down#63]
Is it possibile to force the dropdown to close (same as pressing Done button) from the .js code?
Also, there's no way, as of now, to trigger an "onClose" event, for when the item is selected and confirmed by the user?

I need to save to a database the result of the selection, and I wouldn't want users to think something when wrong, because the list is still opened.

Thanks

**Comment by ickata** [comment]
Will be great to have `onClose` or `onDone` event...
