### ISSUE TITLE
Add support for "isEnabled"

### ISSUE THREAD

**Issue by toddanglin** [PeterStaev/NativeScript-Drop-Down#64]
To make DropDown consistent with other NativeScript UI elements, it would be great if there were support for a `isEnabled` property.

When `isEnabled` is `false` the DropDown should A) not open when tapped, and B) display the label in a disabled state. `isEnabled` should be `true` by default.

**Comment by himanshu331** [comment]
I am not able to reduce the width/distance of the drop down list less than 40%. how can i reduce this?

**Comment by PeterStaev** [comment]
@himanshu331 dont hijack issues and submit a new one describing the problem

**Comment by lukeramsden** [comment]
It seems to work on Android, but just not iOS

**Comment by PeterStaev** [comment]
@lukeramsden , I will have to take a look at this, but it will be for the 3.1 version. Dont think just returning will do. You have to also close the popup. Also not sure about styles.

**Comment by lukeramsden** [comment]
@PeterStaev is there any sort of ETA for 3.1?

**Comment by lukeramsden** [comment]
Styles can be done with pseudo selectors https://github.com/NativeScript/NativeScript/issues/50

**Comment by PeterStaev** [comment]
@lukeramsden , currently there is not ETA for 3.1.
