### ISSUE TITLE
How can I get a dropdown menu button displayed?

### ISSUE THREAD

**Issue by shivapersad** [PeterStaev/NativeScript-Drop-Down#66]
As my topic says I am looking to display an arrow at the end of my Dropdown? Is this possible? I am attempting to do it with CSS. It should look something like the attached.

<img width="161" alt="drop_down_example" src="https://cloud.githubusercontent.com/assets/17012660/22665234/61c998f0-ec8a-11e6-9e0c-677bbbfa7d95.png">

**Comment by PeterStaev** [comment]
Hey @shivapersad , the drop down on iOS does not show an arrow so it matches native controls. You can achieve what you want by greating a `GridLayout` with two columns - one is `*` and will contain the drop down and the second one is as much as the arrow image. Then you should wire the `tap` event of the image to call the `open()` method of the drop down. Hope this helps!

**Comment by shivapersad** [comment]
Hi @PeterStaev, I'll give it a shot. Thanks.
