### ISSUE TITLE
Blank space when there no hint.

### ISSUE THREAD

**Issue by x00** [PeterStaev/NativeScript-Drop-Down#67]
If there is no hint there is a blank space above the other options. If I put a hint the hint fills this space,

**Comment by x00** [comment]
$ tns info
All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬───────────────┐
│ Component        │ Current version │ Latest version │ Information   │
│ nativescript     │ 2.5.0           │ 2.5.0          │ Up to date    │
│ tns-core-modules │ 2.5.0           │ 2.5.0          │ Up to date    │
│ tns-android      │ 2.5.0           │ 2.5.0          │ Up to date    │
│ tns-ios          │                 │ 2.5.0          │ Not installed │
└──────────────────┴─────────────────┴────────────────┴───────────────┘

[ro.board.platform]: [msm8916]
[ro.build.version.sdk]: [23]
[ro.mot.build.version.sdk_int]: [24]
[ro.product.brand]: [motorola]
[ro.product.manufacturer]: [motorola]
[ro.product.model]: [XT1562]
[ro.product.name]: [lux_reteu]
[ro.revision]: [p2c0]

**Comment by PeterStaev** [comment]
Hey @x00 , this is currently by design and i'm not sure will change this. This is becauase this way the first item of the popup comes just below where input control is.

**Comment by x00** [comment]
ok I was going to use this an options menu called from the action bar so it overlays. Works but bit hacky, guess, I need to delve into the code and make my own.

**Comment by x00** [comment]
can you explain this?

https://github.com/PeterStaev/NativeScript-Drop-Down/blob/master/drop-down.android.ts#L261

**Comment by x00** [comment]
setting hint to null before opening works for me. :)

**Comment by PeterStaev** [comment]
Hey @x00 , ok seems I was wrong... Seems I have added ability to hide the "header", and yes you are correct that the hint should be null. Seems currently by default it is empty string. I will see to change the implementation to also check for empty string. Thanks for digging through the code.
