### ISSUE TITLE
Array of string displayed incorrectly in iOS

### ISSUE THREAD

**Issue by eraser2021999** [PeterStaev/NativeScript-Drop-Down#72]
Hello,

I tried to use your control, but it seems there is an issue with iOS: the picker gets each letter as option, see the image below:
<img width="378" alt="screen shot 2017-02-22 at 19 53 51" src="https://cloud.githubusercontent.com/assets/1785284/23224885/a46061a2-f938-11e6-91e7-911b6957975c.png">
Can you help?

**Comment by PeterStaev** [comment]
Hey @eraser2021999 , I suspect you have incorrectly bound the control. Take a look at the demo project in this repo. There you can see how to correctly bind the control to an array of items.

**Comment by PeterStaev** [comment]
No response from user, closing this one for now. In case you still have problems, please reopen and provide more details.
