### ISSUE TITLE
Could you separate the padding value of the value displaying and the popup items

### ISSUE THREAD

**Issue by phattranky** [PeterStaev/NativeScript-Drop-Down#73]
Now set the padding affect to both the value displaying and the popup items
 ```
 #dd
  {
    padding: 10;
}
```

So it's hard to fit the layout, it's always deviation. I have investigated your code, but don't have many exp on native iOS and Android, so i cannot create PR. Thanks in advance

![1](https://cloud.githubusercontent.com/assets/6443154/23832417/23794932-0766-11e7-993b-b3b0db662278.PNG)
![2](https://cloud.githubusercontent.com/assets/6443154/23832418/23a1f76a-0766-11e7-8e78-9fcaa741e6be.PNG)

**Comment by PeterStaev** [comment]
Hey @phattranky , this has always been like this. This way the item in the Android drop down has the same height as the drop down itself. If it is not applied then the items in the popup will be much smaller than the actual drop down.
