### ISSUE TITLE
The list is not rendering item name & shows blank space

### ISSUE THREAD

**Issue by manishmlv50** [PeterStaev/NativeScript-Drop-Down#76]
The dropdown show blank list as shown in the image below : 
This is first time I am getting this error, it works fine regularly

![blank](https://cloud.githubusercontent.com/assets/7044255/24350889/8b4cfecc-1301-11e7-949c-e4bbb04bb5aa.jpg)

And then after restarting the app got this error: 
![error](https://cloud.githubusercontent.com/assets/7044255/24350977/cfa023c4-1301-11e7-94d9-0b4999d03027.jpg)

What can be the error

**Comment by PeterStaev** [comment]
Hey @manishmlv50 , from the screenshots the only guess I have is that there is something wrong with your items - you see that some display the text and some are empty.  If you are using the code in the README make sure you use the code exactly as it is described to.

**Comment by PeterStaev** [comment]
No further response from user, closing this one for now. In case you still have problems, please reopen and provide more details.
