### ISSUE TITLE
Render dynamic dropdown based on json

### ISSUE THREAD

**Issue by tushar-1health** [PeterStaev/NativeScript-Drop-Down#77]
Hi, I have a json form structure of view to be rendered. Based on field type = dropdown, dropdown component should be rendered. If the json structure has one dropdown field type then it works perfectly fine but if there are more than one dropdown fields type it gives error: "Expression has changed after it was checked. Previous value: 'Choose1,Choose2,Choose3'. Current value: 'Half-Yearly,Yearly,Once in Two Years,One Time,Other'."

Could you help me how do I create dynamic dropdowns based on json structure.

**Comment by PeterStaev** [comment]
Hey @tushar-1health , sorry but this is not a place for providing support/assistance. I would suggest to you to post your question by providing more details either on StackOverflow or on the [Nativescript forums](https://discourse.nativescript.org/) and someone from the community might be willing to help you.
