### ISSUE TITLE
Drop down won't open

### ISSUE THREAD

**Issue by enoonan** [PeterStaev/NativeScript-Drop-Down#78]
Even just copying and pasting code straight from the demo app, I'm not able to get this to work. I'm working on an iOS app, specifically for iPad. 

The text from the demo displays, and if I change the selectedIndex from e.g. 1 to 2 in the controller declaration, the correct "data item 2" string displays. But when I click on any part of it (I'm using an emulator) there is no effect. No errors are logged to the console.

I expect a UIPickerView / spinner to appear at the bottom of the screen, but nothing happens. I've rebuilt the project several times, uninstalled and reinstalled the app on my emulator - still the same result.

Any idea what could be causing this?

**Comment by PeterStaev** [comment]
Hey @enoonan , I just tried running the demo app in iPad2 simulator and it works fine. So there must be some problem with your setup.

**Comment by enoonan** [comment]
That's what I was afraid of. Thanks for checking it out.

Eileen Noonan
Developer
Laravel, Angular, Wordpress

**Comment by philpalmieri** [comment]
Did you ever figure out what it was?  I'm having the same issue with tns 3.0

**Comment by enoonan** [comment]
Nope. In the end our client just wanted a TextField so it became moot for
the time being

Eileen Noonan
Developer
Laravel, Angular, Wordpress

**Comment by philpalmieri** [comment]
crud... its working on android, not ios - im hoping its just a version issue

**Comment by philpalmieri** [comment]
Just for anyone else, I found the issue/solution... I had not upgraded xcode and the emulator in a while, after doing that it works as expected

**Comment by enoonan** [comment]
I can confirm my Xcode was out of date when I was having this problem

Eileen Noonan
Developer
Laravel, Angular, Wordpress
