### ISSUE TITLE
Working with value and display members

### ISSUE THREAD

**Issue by slasho** [PeterStaev/NativeScript-Drop-Down#83]
I cant get it work, on plain JS (Vanilla) can anyone help please.

**Comment by PeterStaev** [comment]
Take a look at https://github.com/PeterStaev/NativeScript-Drop-Down/issues/2#issuecomment-164742964 this contains the JS implementation of the `ValueList` class. Also you can download the demo app in this repo, compile it and then look at the generated JS files.
