### ISSUE TITLE
Is the core3 branch working at this point?

### ISSUE THREAD

**Issue by alexziskind1** [PeterStaev/NativeScript-Drop-Down#85]
Hi Peter,
I see you are testing the plugin with the 3 rc release. Does it currently work in the state that it's in?

Thanks!

**Comment by PeterStaev** [comment]
Hey Alex, 
Yes, it should be working (at least with RC1, not sure if they have released a new rc that broke something 😄 ). There is also an RC tag on NPM so you can install it directly with `$tns plugin add nativescript-drop-down@rc`. If you experience any problems, feel free to log them as issues ;)
