### ISSUE TITLE
Drop-down selection gets cleared.

### ISSUE THREAD

**Issue by jsagar92** [PeterStaev/NativeScript-Drop-Down#87]
Hello,
I am using nativescript-drop-down in tabview. I have 6 tabs on that page.
My all tabs are on same page. I have bound observable property to drop-downs selected index.
But when I change tabs couple of times , drop downs selection gets cleared.
Don't  know what to do. Please help.

Thanks in advance.

**Comment by PeterStaev** [comment]
@jsagar92 , seems this relates to something specific in your code. Would be good if you can provide some simple demo repro.

**Comment by jsagar92** [comment]
Hello @PeterStaev ,
Thank you for your quick reply.
I am attaching my xml, js and view-model.js.
Please have  a look at them and let me know If I am doing anything wrong.

Thanks again.
[farmer_registration.js.txt](https://github.com/PeterStaev/NativeScript-Drop-Down/files/954778/farmer_registration.js.txt)
[farmer_registration.xml.txt](https://github.com/PeterStaev/NativeScript-Drop-Down/files/954779/farmer_registration.xml.txt)
[farmers-view-model.js.txt](https://github.com/PeterStaev/NativeScript-Drop-Down/files/954780/farmers-view-model.js.txt)

**Comment by PeterStaev** [comment]
Hey @jsagar92 , can you please isolate the issue in some small demo project? The attached files have lots of things in them, and tracing problems there will be very hard.

**Comment by philpalmieri** [comment]
this might be related to my issue: https://github.com/PeterStaev/NativeScript-Drop-Down/issues/95 I was able to reproduce it on a vanilla project

**Comment by PeterStaev** [comment]
Hey @jsagar92 , can you please try the 3.0.1 version now available on nom and see if that will resolve your problem as well?

**Comment by PeterStaev** [comment]
No further response so closing this one for now. In case you still have problems, please reopen and provide more details.
