### ISSUE TITLE
Invisible labels

### ISSUE THREAD

**Issue by eleddie** [PeterStaev/NativeScript-Drop-Down#90]
Hi, I'm getting an rare behavior when I programmatically change the index of the dropdown.

The dropdown has these values
<img width="233" alt="screen shot 2017-04-26 at 10 49 07 pm" src="https://cloud.githubusercontent.com/assets/13477629/25566548/ff7325b2-2da8-11e7-8ea9-aaeed515c7b9.png">

But when I change the index (It's a master details view, so when I tap on an item in the left list, the values on the right panel get updated) the value of the dropdown changes without problem, but when I tap on the dropdown to show the values again, it looks like this:
<img width="232" alt="screen shot 2017-04-26 at 10 49 18 pm" src="https://cloud.githubusercontent.com/assets/13477629/25566571/68000adc-2da9-11e7-923b-b2baed527a94.png">

Any ideas?

**Comment by PeterStaev** [comment]
This has been reported by someone else as well, but there seems problem was with `null` values. Can you provide some reproducible demo project? Also can you try if you see the same problem with the 3.0 RC version?

**Comment by mcrvaz** [comment]
I'm having a similar issue, the selected element is always invisible. Also, the drop-down size is too small, I had to add some padding to it.
Here is the example:
[item-detail.component.html](https://gist.github.com/mcrvaz/2ac787bc95345ac8799d3c6391515e54)  
[item-detail.component.ts](https://gist.github.com/mcrvaz/6f46212453c1cc94b007cec42c07718d)

**Comment by celsomtrindade** [comment]
Running into the same issue. Some times the labels reapear after selecting a random option. Sometimes it stays blank. Sometimes I even see an extra blank option, for example, if I have 5 options, I see those 5 options but with a big space in between like a blank option addedd.

**Comment by PeterStaev** [comment]
The fix will be available in the 3.1 version.
