### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by miaupip** [PeterStaev/NativeScript-Drop-Down#92]
Hy, 
Im getting some errors when i try to use the nativescript-drop-down.
The errors I got are:

`node_modules/nativescript-drop-down/drop-down.d.ts(41,14): error TS2304: Cannot find name 'UILabel'.
node_modules/nativescript-drop-down/drop-down.d.ts(42,18): error TS2694:  Cannot find namespace 'android'. `
 
It's tested with the typescript version: 2.1.6
on android

Test Project, the dropdown is added in app/item/items.component.html  and app/item/items.component.ts:
[MyNextGreatApp.zip](https://github.com/PeterStaev/NativeScript-Drop-Down/files/973186/MyNextGreatApp.zip)

Have someone some ideas, how this can be fixed?

**Comment by PeterStaev** [comment]
Hey @miaupip , you can see https://github.com/PeterStaev/NativeScript-Drop-Down/issues/39 and more specifically https://github.com/PeterStaev/NativeScript-Drop-Down/issues/39#issuecomment-252548468. 

In version 3.0 I've removed the strong typing of the definitions, so you can also upgrade to the new version (**require TNS 3.0!**)
