### ISSUE TITLE
Unable to modify text alignment

### ISSUE THREAD

**Issue by laurianem** [PeterStaev/NativeScript-Drop-Down#94]
Hi, 
I'm trying to get the text in the dropdown vertically centered in the text input (see pictures).
I've tried using css with line-height property and padding-top but nothing seems to work. Are these css properties supported for the dropdown?

<img width="466" alt="screen shot 2017-05-08 at 6 00 24 pm" src="https://cloud.githubusercontent.com/assets/27816478/25827308/8ffa36d2-3418-11e7-9d94-caa62f865860.png">

<img width="497" alt="screen shot 2017-05-08 at 6 00 31 pm" src="https://cloud.githubusercontent.com/assets/27816478/25827314/95bf50d4-3418-11e7-8d3d-6afb30c26804.png">

My code looks like this : 

`<DropDown class="form-item language-dropdown"
                          [class.error-form]="_formGroup.get('culture').invalid"
                          formControlName="culture"
                          returnKeyType="done"
                          horizontalAlignment="stretch"
                          verticalALignment="stretch"
                          (returnPress)="_formGroup.get('culture').enable()"
                          (opened)="_formGroup.get('culture').value === (null||undefined||'') && _formGroup.get('culture').setValue(0)"
                          [items]="cultureLabels">
                </DropDown>`

Thanks!

**Comment by PeterStaev** [comment]
Hey @laurianem , I've just tested with the demo-ng project and padding-top is applied correctly. I see you are applying multiple classes to the drop down, so make sure some does not override your values, or some CSS rules are more specific and do not apply your padding. I would suggest you remove all your classes and make one new class with the padding, and the start adding back the other classes and see which one is overriding it.

**Comment by laurianem** [comment]
Yeah you are right, I had CSS conflict somewhere else. Thanks for you time, very appreciated!
