### ISSUE TITLE
NG4 TNS3 DropDown clears after return navigation (iOS only)

### ISSUE THREAD

**Issue by philpalmieri** [PeterStaev/NativeScript-Drop-Down#95]
![screen recording 2017-05-10 at 09 26 am](https://cloud.githubusercontent.com/assets/170333/25900893/fdf12434-3562-11e7-9c4f-99f573ce979c.gif)

The DropDownModule seems to lose binding to the UIPickerViewDataSource (or the owner reference in DropDownListDataSource) on 'back' navigation in iOS only - works in android... I'm only able to test in ios 10.3, this was not happening in 1.5 on ios 9 before the NG4 build

# Reproduce
- Build a dropdown with a list of items
- Navigate to a new page
- use the built in back button on ios
- the spinner is now cleared, and closing/re-opening continues to be cleared

# clean demo repository
- https://github.com/philpalmieri/nativescript-dropdown-navigation-bug
- (ValueList) Version https://github.com/philpalmieri/nativescript-dropdown-navigation-bug/tree/valuelist-version

**Comment by PeterStaev** [comment]
Hey @philpalmieri , this should be fixed with the 3.0.1 version available now on npm.

**Comment by philpalmieri** [comment]
Awesome, thank you so much
