### ISSUE TITLE
JS: ERROR Error: Uncaught (in promise): TypeError: Could not load view for: DropDown.Error: com.tns.NativeScriptException: Failed to find module: "ui/core/proxy", relative to: app/tns_modules/

### ISSUE THREAD

**Issue by longfay** [PeterStaev/NativeScript-Drop-Down#98]
I found this error when running on Android.. Anyone have an idea? Thanks!

`JS: ERROR Error: Uncaught (in promise): TypeError: Could not load view for: DropDown.Error: com.tns.NativeScriptException: Failed to find module: "ui/core/proxy", relative to: app/tns_modules/`

**Comment by PeterStaev** [comment]
Hey @longfay , seems you are using an old version of the plugin with TNS 3.0. You should upgrade the plugin to version 3.0.1 which is fully compatible with TNS 3.0.

**Comment by longfay** [comment]
@PeterStaev Thanks!! It works now 👍
