### ISSUE TITLE
Angular module does not work with @next (>3.0.0) version of nativescript-angular

### ISSUE THREAD

**Issue by jakoguta** [PeterStaev/NativeScript-Drop-Down#99]
I managed to work with the plugin well at first then later when I deleted my `node_modules` and run `tns run android` (Using the NativeScript `sample-Groceries` project) it fails with the error mentioned above.

**How to recreate the problem**

- Download and setup the sample project [NativeScript sample-Groceries](https://github.com/NativeScript/sample-Groceries).
- Add the plugin to the `package.json` i.e. `"nativescript-drop-down": "^3.0.1"`
- Go to `groceries.module.ts` and add `import { DropDownModule } from "nativescript-drop-down/angular"`, also add the Module to the `@NgModule` imports section just as the plugin specifies.
- Run `tns run android`.

The error should appear after the build completes in the emulator.

My development environment:
- npm version: 4.6.1
- tns version: 3.0.1
- node: 6.10.3

**Comment by PeterStaev** [comment]
Hey @jakoguta , the groceries app uses "next" version of nativescript-angular which is currently not supported. You must use the latest stable version `3.0.0` and there should be no problems.

**Comment by jakoguta** [comment]
Well noted, I have reverted back to `3.0.0` and it works fine.

**Comment by suresh-selvaraj** [comment]
We trying to run demo-ng application, below error is returned

Registry returned 404 for GET on https://registry.npmjs.org/nativescript-dev-ios

Kindly let us know how to run the demo-ng app in Mac machine

**Comment by PeterStaev** [comment]
@suresh-selvaraj there seems to be a NPM problem on the machine that is unrelated to the demo/plugin. Also please do not hijack issues but submit new ones.
